[Client]
    dsn = "goblin:y7aRtNLjSD3FmkqdCMiK1lofbrvuwT9z@tcp(172.22.34.101:3308)/bilibili_goblin?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 5
    idle = 5
    idleTimeout = "4h"
