package model

type MaterialType string

const (
	MaterialArchive           = MaterialType("archive")
	MaterialLive              = MaterialType("live") //直播id
	MaterialGame              = MaterialType("game") //游戏id
	MaterialEpisode           = MaterialType("episode")
	MaterialArticle           = MaterialType("article")
	MaterialLiveRoom          = MaterialType("live_room")
	MaterialFolder            = MaterialType("folder")
	MaterialAccount           = MaterialType("account")
	MaterialMixExtsRly        = MaterialType("mix_exts_rly")         //NaPageClient.ModuleMixExts
	MaterialActSubProto       = MaterialType("act_subject_protocol") //活动和扩展信息
	MaterialHasDynsRly        = MaterialType("dyntopic_has_dyns_rly")
	MaterialListDynsRly       = MaterialType("dyntopic_list_dyns_rly")
	MaterialDynDetail         = MaterialType("dyn_detail")
	MaterialActLikesRly       = MaterialType("activity_act_likes_rly")
	MaterialDynRevsRly        = MaterialType("dyn_revs_rly")
	MaterialTag               = MaterialType("tag")
	MaterialGetHisRly         = MaterialType("actplat_has_his_rly")
	MaterialPageArcsRly       = MaterialType("popular_page_arcs_rly")
	MaterialMixExtRly         = MaterialType("mix_ext_rly")
	MaterialRankRstRly        = MaterialType("activity_rank_rst_rly")
	MaterialSelSerieRly       = MaterialType("appshow_selected_serie_rly")
	MaterialUpListRly         = MaterialType("activity_up_list_rly")
	MaterialRelInfosRly       = MaterialType("character_rel_infos_rly")
	MaterialBriefDynsRly      = MaterialType("dyntopic_brief_dyns_rly")
	MaterialQueryWidRly       = MaterialType("pgcapp_query_wid_rly")
	MaterialRoomsByActIdRly   = MaterialType("liveplay_rooms_by_actid_rly")
	MaterialArcPlayer         = MaterialType("arc_player")
	MaterialChannelFeedRly    = MaterialType("hmt_channel_feed_rly")
	MaterialRelation          = MaterialType("relation")
	MaterialAccountCard       = MaterialType("account_card")
	MaterialNativeCard        = MaterialType("native_card")
	MaterialNativeAllPage     = MaterialType("native_all_page")
	MaterialNativePages       = MaterialType("native_pages")
	MaterialWeeks             = MaterialType("weeks")
	MaterialChannel           = MaterialType("channel")
	MaterialVoteRankRly       = MaterialType("activity_vote_rank_rly")
	MaterialUpRsvInfo         = MaterialType("up_reserve_relation_info")
	MaterialRoomSessionInfo   = MaterialType("xroom_session_info_rly")
	MaterialTimelineRly       = MaterialType("popular_timeline_rly")
	MaterialSeasonCard        = MaterialType("pgcapp_season_card_info")
	MaterialSeasonByPlayIdRly = MaterialType("pgcapp_season_by_playid_rly")
	MaterialActiveUsersRly    = MaterialType("dyntopic_get_active_users_rly")
	MaterialDynVoteInfo       = MaterialType("dynvote_vote_info")
	MaterialActSubject        = MaterialType("activity_act_subject")
	MaterialActProgressGroup  = MaterialType("activity_act_progress_group")
	MaterialSourceDetail      = MaterialType("biz_source_detail_rly")
	MaterialProductDetail     = MaterialType("biz_product_detail_rly")
	MaterialPgcFollowStatus   = MaterialType("pgcfollow_status")
	MaterialComicInfo         = MaterialType("comic_info")
	MaterialActReserveFollow  = MaterialType("activity_reserve_follow")
	MaterialActAwardState     = MaterialType("activity_award_state")
	MaterialTicketFavState    = MaterialType("mall_ticket_fav_state")
	MaterialActRelationInfo   = MaterialType("activity_relation_info")
	MaterialPlatCounterRes    = MaterialType("actplat_counter_res")
	MaterialPlatTotalRes      = MaterialType("actplat_total_res")
	MaterialLotteryUnused     = MaterialType("activity_lottery_unused_times")
	MaterialScoreTarget       = MaterialType("commscore_score_target")
)
