// Code generated by kratos tool btsgen. DO NOT EDIT.

/*
  Package wechat is a generated cache proxy package.
  It is generated from:
  type _bts interface {
		// cache
		AccessToken(c context.Context) (*wechat.AccessToken, error)
	}
*/

package wechat

import (
	"context"

	"go-common/library/net/metadata"
	"go-common/library/stat/prom"
	"go-gateway/app/web-svr/web-goblin/interface/model/wechat"
)

var _ _bts

// AccessToken get data from cache if miss will call source method, then add to cache.
func (d *Dao) AccessToken(c context.Context) (res *wechat.AccessToken, err error) {
	addCache := true
	res, err = d.CacheAccessToken(c)
	if err != nil {
		addCache = false
		err = nil
	}
	if res != nil {
		prom.CacheHit.Incr("AccessToken")
		return
	}
	prom.CacheMiss.Incr("AccessToken")
	res, err = d.RawAccessToken(c)
	if err != nil {
		return
	}
	var miss = res
	if !addCache {
		return
	}
	d.cache.Do(c, func(c context.Context) {
		d.AddCacheAccessToken(metadata.WithContext(c), miss)
	})
	return
}
