CREATE TABLE IF NOT EXISTS `score_analysis_lol_team` (
    `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    `tournament_id` int(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '联赛ID',
    `team_id` int(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '队伍ID',
    `team_name` varchar(128) NOT NULL DEFAULT '' COMMENT '队伍简称',
    `image` varchar(512) NOT NULL DEFAULT '' '队伍图标',
    `kda` decimal(4,1) NOT NULL DEFAULT 0 COMMENT 'kda值',
    `total_round` int(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '比赛场数',
    `avg_round_duration` varchar(128) NOT NULL DEFAULT '' COMMENT '场均时长',
    `first_blood_rate` decimal(4,1) NOT NULL DEFAULT 0 COMMENT '一血率',
    `avg_kills` decimal(4,1) NOT NULL DEFAULT 0 COMMENT '场均击杀',
    `avg_assists` decimal(4,1) NOT NULL DEFAULT 0 COMMENT '场均助攻',
    `avg_deaths` decimal(4,1) NOT NULL DEFAULT 0 COMMENT '场均死亡',
    `avg_damage` decimal(4,1) NOT NULL DEFAULT 0 COMMENT '场均输出',
    `avg_damage_min` decimal(4,1) NOT NULL DEFAULT 0 COMMENT '分均输出',
    `avg_hits_min` decimal(4,1) NOT NULL DEFAULT 0 COMMENT '分均补刀',
    `avg_economy` decimal(10,1) NOT NULL DEFAULT 0 COMMENT '场均经济',
    `avg_economy_min` decimal(10,1) NOT NULL DEFAULT 0 COMMENT '分均经济',
    `avg_small_dargon` decimal(4,1) NOT NULL DEFAULT 0 COMMENT '场均小龙',
    `small_dargon_rate` decimal(4,1) NOT NULL DEFAULT 0 COMMENT '小龙控制率',
    `avg_wards_placed_min` decimal(4,1) NOT NULL DEFAULT 0 COMMENT '分均插眼数',
    `avg_wards_killed_min` decimal(4,1) NOT NULL DEFAULT 0 COMMENT '分均排眼数',
    `avg_towers_destroyed` decimal(4,1) NOT NULL DEFAULT 0 COMMENT '场均推塔数',
    `avg_towers_be_destroyed` decimal(4,1) NOT NULL DEFAULT 0 COMMENT '场均被推塔数',
    `avg_big_dargon` decimal(4,1) NOT NULL DEFAULT 0 COMMENT '场均大龙',
    `big_dargon_rate` decimal(4,1) NOT NULL DEFAULT 0 COMMENT '大龙控制率',
    `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'score更新时间',
    `win` int(4) UNSIGNED NOT NULL DEFAULT 0 COMMENT '比赛胜场数',
    `lose` int(4) UNSIGNED NOT NULL DEFAULT 0 COMMENT '比赛负场数',
    `win_rate` decimal(4,1) NOT NULL DEFAULT 0 COMMENT '胜率',
    `small_rounds` int(4) UNSIGNED NOT NULL DEFAULT 0 COMMENT '小局数',
    `score` decimal(5,1) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Score评分',
    `total_kills` int(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '总击杀',
    `total_deaths` int(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '总死亡',
    `total_small_dargon` int(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '总小龙',
    `total_big_dargon` int(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '总大龙',
    `total_assists` int(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '总助攻',
    `ctime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `mtime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    PRIMARY KEY (`id`),
    KEY `ix_mtime` (`mtime`),
    UNIQUE KEY `ix_tournament_team_id` (`tournament_id`, `team_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT = 'score战队数据榜';

CREATE TABLE IF NOT EXISTS `score_analysis_lol_player` (
    `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    `tournament_id` int(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '联赛ID',
    `player_id` int(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '选手ID',
    `player_name` varchar(128) NOT NULL DEFAULT '' COMMENT '选手昵称',
    `player_en_name` varchar(128) NOT NULL DEFAULT '' COMMENT '选手姓名',
    `image` varchar(512) NOT NULL DEFAULT '' COMMENT '选手图标',
    `team_id` int(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '队伍ID',
    `team_name` varchar(128) NOT NULL DEFAULT '' COMMENT '队伍简称',
    `team_image` varchar(512) NOT NULL DEFAULT '' COMMENT '队伍图标',
    `position_name` varchar(128) NOT NULL DEFAULT '' COMMENT '位置名称',
    `position_id` int(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '位置ID',
    `kda` decimal(4,1) NOT NULL DEFAULT 0 COMMENT 'kda值',
    `played` int(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '出场次数',
    `participate_rate` decimal(4,1) NOT NULL DEFAULT 0 COMMENT '参团率',
    `avg_kills` decimal(10,1) NOT NULL DEFAULT 0 COMMENT '场均击杀',
    `avg_assists` decimal(10,1) NOT NULL DEFAULT 0 COMMENT '场均助攻',
    `avg_deaths` decimal(10,1) NOT NULL DEFAULT 0 COMMENT '场均死亡',
    `avg_economy_min` decimal(10,1) NOT NULL DEFAULT 0 COMMENT '分均经济',
    `avg_hits_min` decimal(10,1) NOT NULL DEFAULT 0 COMMENT '分均补刀',
    `avg_damage_min` decimal(10,1) NOT NULL DEFAULT 0 COMMENT '分均输出',
    `avg_damage_taken_min` decimal(10,1) NOT NULL DEFAULT 0 COMMENT '分均承伤',
    `damage_rate` decimal(4,1) NOT NULL DEFAULT 0 COMMENT '输出占比',
    `damage_taken_rate` decimal(4,1) NOT NULL DEFAULT 0 COMMENT '承伤占比',
    `avg_wards_placed_min` decimal(10,1) NOT NULL DEFAULT 0 COMMENT '分均插眼数',
    `avg_wards_killed_min` decimal(10,1) NOT NULL DEFAULT 0 COMMENT '分均排眼数',
    `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'score更新时间',
    `mvp` int(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'MVP次数',
    `win` int(4) UNSIGNED NOT NULL DEFAULT 0 COMMENT '比赛胜场数',
    `lose` int(4) UNSIGNED NOT NULL DEFAULT 0 COMMENT '比赛负场数',
    `win_rate` decimal(4,1) NOT NULL DEFAULT 0 COMMENT '胜率',
    `country_id` int(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '国家ID',
    `country_image` varchar(128) NOT NULL DEFAULT '' COMMENT '国旗图标',
    `score` decimal(5,1) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Score评分',
    `total_kills` int(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '总击杀',
    `total_deaths` int(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '总死亡',
    `total_assists` int(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '总助攻',
    `ctime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `mtime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    PRIMARY KEY (`id`),
    KEY `ix_mtime` (`mtime`),
    UNIQUE KEY `ix_tournament_player_id` (`tournament_id`, `player_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT = 'score选手数据榜';

CREATE TABLE IF NOT EXISTS `score_analysis_lol_hero` (
    `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    `tournament_id` int(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '联赛ID',
    `hero_id` int(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '英雄ID',
    `hero_name` varchar(128) NOT NULL DEFAULT '' COMMENT '英雄名称',
    `hero_en_name` varchar(128) NOT NULL DEFAULT '' COMMENT '英雄英文名称',
    `hero_tw_name` varchar(128) NOT NULL DEFAULT '' COMMENT '英雄繁体名称',
    `image` varchar(512) NOT NULL DEFAULT '' COMMENT '英雄图标',
    `position_id` int(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '位置ID',
    `position_name` varchar(128) NOT NULL DEFAULT '' COMMENT '位置名称',
    `kda` decimal(4,1) NOT NULL DEFAULT 0 COMMENT 'kda值',
    `picked` int(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '出场数',
    `picked_rate` decimal(4,1) NOT NULL DEFAULT 0 COMMENT '出场率',
    `baned` int(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '被禁场数',
    `baned_rate` decimal(4,1) NOT NULL DEFAULT 0 COMMENT '被禁率',
    `win_rate` decimal(4,1) NOT NULL DEFAULT 0 COMMENT '胜率',
    `win` int(4) UNSIGNED NOT NULL DEFAULT 0 COMMENT '比赛胜场数',
    `total_round` int(4) UNSIGNED NOT NULL DEFAULT 0 COMMENT '比赛场数',
    `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'score更新时间',
    `score` decimal(5,1) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Score评分',
    `avg_kills` decimal(10,1) NOT NULL DEFAULT 0 COMMENT '场均击杀',
    `avg_assists` decimal(10,1) NOT NULL DEFAULT 0 COMMENT '场均助攻',
    `avg_deaths` decimal(10,1) NOT NULL DEFAULT 0 COMMENT '场均死亡',
    `game_version` varchar(128) NOT NULL DEFAULT '' COMMENT '游戏版本',
    `ctime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `mtime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    PRIMARY KEY (`id`),
    KEY `ix_mtime` (`mtime`),
    UNIQUE KEY `ix_tournament_hero_id` (`tournament_id`, `hero_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT = 'score英雄数据榜';
