[ArcNotify]
    key = "8e27ab7e39270b59"
    secret = "477df6a068d7332a163f95abbad2079c"
    group = "ArchiveNotify-MainAppSvr-Steins-S"
    topic = "ArchiveNotify-T"
    action = "sub"
[SteinsGate]
    key = "8e27ab7e39270b59"
    secret = "477df6a068d7332a163f95abbad2079c"
    group = "SteinsGate-MainAppSvr-P"
    topic = "SteinsGate-T"
    action = "pub"
    proto = "tcp"
    addr = "172.18.33.50:6205"
    idle = 100
    active = 100
    dialTimeout = "1s"
    readTimeout = "60s"
    writeTimeout = "1s"
    idleTimeout = "10s"
[SteinsEvaluation]
    key = "8e27ab7e39270b59"
    secret = "477df6a068d7332a163f95abbad2079c"
    group = "SteinsEvaluation-MainAppSvr-S"
    topic = "SteinsEvaluation-T"
    action = "pub"
    proto = "tcp"
    addr = "172.18.33.50:6205"
    idle = 100
    active = 100
    dialTimeout = "1s"
    readTimeout = "60s"
    writeTimeout = "1s"
    idleTimeout = "10s"