
loadWhitelistSpec = "@every 1s"

[vendorID]
    "wzyd" = "2"

[ipWhitelist]
    "wzyd" = []

[host]
    mgr = "manager.bilibili.co"

[httpMgr]
    key    = "e7482d29be4a95b8"
    secret = "9e803791cdef756e75faee68e12b7442"
    dial      = "500ms"
    timeout   = "1s"
    keepAlive = "60s"