[admin]
    name = "app-thirdsdk/admin"
    proto = "tcp"
    addr = "127.0.0.1:26614"
    idle = 10
    active = 10
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "10s"