[Client]
	addr = "127.0.0.1:3306"
	# dsn = "test:test@tcp(172.16.33.205:3308)/bilibili_lottery?timeout=1s&readTimeout=1s&writeTimeout=1s&parseTime=true&loc=Local&charset=utf8mb4,utf8"
	#readDSN = ["test:test@tcp(172.16.33.205:3308)/bilibili_lottery?timeout=1s&readTimeout=1s&writeTimeout=1s&parseTime=true&loc=Local&charset=utf8mb4,utf8",]

	dsn = "test_3306:UJPZaGKjpb2ylFx3HNhmLuwOYft4MCAi@tcp(172.22.34.101:lottery:D8B9aJcnMHh2SWzVvCQiIJ2qYzfMvfUg@tcp(172.22.34.101:3306)/bilibili_lottery?timeout=10s&readTimeout=10s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4)/bilibili_lottery?timeout=10s&readTimeout=10s&writeTimeout=10s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    readDSN = ["test_3306:UJPZaGKjpb2ylFx3HNhmLuwOYft4MCAi@tcp(172.22.34.101:3306)/bilibili_lottery?timeout=10s&readTimeout=10s&writeTimeout=10s&parseTime=true&loc=Local&charset=utf8,utf8mb4",]


	active = 20
	idle = 10
	idleTimeout ="4h"
	queryTimeout = "5s"
	execTimeout = "5s"
	tranTimeout = "5s"

[steinsgate]
addr = "172.16.33.205:3308"
dsn = "test_3306:UJPZaGKjpb2ylFx3HNhmLuwOYft4MCAi@tcp(172.22.34.101:3306)/steins_gate?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
active = 20
idle = 10
idleTimeout ="4h"
queryTimeout = "1s"
execTimeout = "1s"
tranTimeout = "2s"