
#http
[server]
    addr = "0.0.0.0:8000"
    timeout = "1s"

[mysql]
    [mysql.steinsgate]
    addr = "172.16.33.205:3308"
    dsn = "test_3306:UJPZaGKjpb2ylFx3HNhmLuwOYft4MCAi@tcp(172.22.34.101:3306)/steins_gate?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 5
    idle = 2
    idleTimeout ="4h"
    queryTimeout = "1s"
    execTimeout = "1s"
    tranTimeout = "2s"
    [mysql.steinsgate.breaker]
        window = "3s"
        sleep = "100ms"
        bucket = 10
        ratio = 0.5
        request = 100

[httpClient]
    key    = "7c7ac0db1aa05587"
    secret = "9a6d62d93290c5f771ad381e9ca23f26"
    dial = "80ms"
    timeout = "500ms"
    keepAlive = "60s"
    timer = 1000

[videoClient]
    key    = "7c7ac0db1aa05587"
    secret = "9a6d62d93290c5f771ad381e9ca23f26"
    dial = "80ms"
    timeout = "500ms"
    keepAlive = "60s"
    timer = 1000

[Xlog]
    dir = "/data/log/steins-gate-service/"
    stdout = true

[Host]
    videoUp = "http://archive.api.bilibili.co"
    bvc = "http://172.16.38.189:7086"

[bvc]
    key = "d5487ea02b97"