[Databus]
    target = "discovery://default/infra.databus.v2"
    app_id = "main.web-svr.esports"
    token = "4b6359ee1471e91fdece8e113204fcad"
    [Databus.Topic]
    BGroupMessage = "BGroupMessage-T"
    ContestSchedule = "ContestSchedule-Uat-T"

[TunnelDatabusPub]
    key = "170e302355453683"
    secret = "3d0e8db7bed0503949e545a469789279"
    group = "TunnelRelation-MainCommunity-P"
    topic = "TunnelRelation-T"
    action = "pub"
    dialTimeout = "60ms"
    readTimeout = "200ms"
    writeTimeout = "500ms"
    idleTimeout = "10s"

[ArchiveNotifySub]
    key = "9765cdac5894f2ba"
    secret = "f4237d712c3ed1e7fab0137b81418b14"
    group = "ArchiveNotify-MainWebSvr-Esports-S"
    topic = "ArchiveNotify-T"
    action = "sub"

[EsportsBinlog]
    key = "9765cdac5894f2ba"
    secret = "f4237d712c3ed1e7fab0137b81418b14"
    group = "EsportsBinlog-MainWebSvr-Esports-S"
    topic = "EsportsBinlog-T"
    action = "sub"