# This is a TOML document. Boom.

version = "1.0.0"
user    = "nobody"
pid     = "/tmp/app-wall.pid"
dir     = "./"
family = "app-wall"
checkFile = "/data/www/wall.html"

[unicomDatabus]
    key = "8e27ab7e39270b59"
    secret = "4b8c2e03c48f0b21eacd7a11e2a3b003"
    group = "UnicomWelfareClub-MainAppSvr-P"
    topic = "UnicomWelfareClub-T"
    action = "pub"
    offset = "new"
    name = "unicom-order/sub"
    proto = "tcp"
    addr = "172.18.21.41:6205"
    active = 1
    idle = 1
    dialTimeout = "1s"
    readTimeout = "60s"
    writeTimeout = "1s"
    idleTimeout = "10s"

[host]
apiCo               = "http://uat-api.bilibili.co"
dotin               = "http://svr.dotinapp.com"
live                = "http://inner.live.bilibili.co"
apiLive             = "http://api.live.bilibili.co"
telecom             = "https://open.fg.21cn.com"
unicom              = "http://123.125.99.7:9001"
unicomFlow          = "http://open.10010.com"
broadband           = "http://114.255.201.238:8092"
sms                 = "http://uat-api.bilibili.co"
mall                = "http://uat-mall.bilibili.co"
telecomReturnURL    = "http://www.bilibili.com/blackboard/preview/activity-telecom2017.html?biliStatus=1"
telecomCancelPayURL = "http://www.bilibili.com/blackboard/preview/activity-telecom2017.html"
telecomActive       = "https://openeop.dcoos.189.cn:8000"
comic               = "http://manga.bilibili.co"
gdt                 = "http://t.gdt.qq.com"

[log]
Dir = "/data/log/app-wall/"
	[log.syslog]
        project  = "app-wall"
        proto    = "udp"
        addr     = "172.18.19.22:9999"
        chansize = 10240

[statsd]
project  = "app-wall"
addr     = "172.18.20.15:8200"
chanSize = 1024

[app]
key    = "e7482d29be4a95b8"
secret = "9e803791cdef756e75faee68e12b7442"

[httpClient]
key    = "e7482d29be4a95b8"
secret = "9e803791cdef756e75faee68e12b7442"
dial      = "500ms"
timeout   = "2s"
keepAlive = "60s"
timer     = 10
    [httpClient.breaker]
    window  = "3s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100

[httpTelecom]
key    = "e7482d29be4a95b8"
secret = "9e803791cdef756e75faee68e12b7442"
dial      = "500ms"
timeout   = "50s"
keepAlive = "60s"
timer     = 10
    [httpTelecom.breaker]
    window  = "3s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100

[HTTPBroadband]
key    = "e7482d29be4a95b8"
secret = "9e803791cdef756e75faee68e12b7442"
dial      = "500ms"
timeout   = "4s"
keepAlive = "60s"
timer     = 10
    [HTTPBroadband.breaker]
    window  = "3s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100

[HTTPUnicom]
key    = "e7482d29be4a95b8"
secret = "9e803791cdef756e75faee68e12b7442"
dial      = "500ms"
timeout   = "4s"
keepAlive = "60s"
timer     = 10
    [HTTPUnicom.breaker]
    window  = "3s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100

[httpActive]
key    = "e7482d29be4a95b8"
secret = "9e803791cdef756e75faee68e12b7442"
dial      = "500ms"
timeout   = "2s"
keepAlive = "60s"
timer     = 10
    [httpActive.breaker]
    window  = "3s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100

[HTTPActivate]
key    = "e7482d29be4a95b8"
secret = "9e803791cdef756e75faee68e12b7442"
dial      = "500ms"
timeout   = "50s"
keepAlive = "60s"
timer     = 10
    [HTTPActivate.breaker]
    window  = "3s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100

[bm]
    [bm.outer]
    addr = "0.0.0.0:6251"
    timeout = "5s"
    readTimeout = "5s"
    writeTimeout = "5s"

[mysql]
    [mysql.show]
    dsn    = "test:test@tcp(172.16.33.205:3308)/bilibili_show?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 5
    idle   = 2
    idleTimeout ="2h"
    queryTimeout = "1s"
    execTimeout = "1s"
    tranTimeout = "1s"
    [mysql.showLog]
    dsn    = "test:test@tcp(172.16.33.205:3308)/bilibili_show?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 5
    idle   = 2
    idleTimeout ="2h"
    queryTimeout = "10s"
    execTimeout = "1s"
    tranTimeout = "1s"

[seq]
    businessID =1
    token      ="Y1zHA2esXfd2T6bc1VRHkFWryD01Aswi"

[seqRPC]
    pullInterval = "10s"
    timeout = "200ms"

[iplimit]
mobileIPFile = "/data/conf/operate/mobileip.txt"
[iplimit.addrs]
	unicom  = ["127.0.0.1", "111.206.133.54", "114.255.201.224", "111.206.133.34", "111.8.57.60", "111.197.4.233"]
    telecom = ["127.0.0.1"]

[redis]
	[redis.recommend]
	name   = "app-show/recommend"
	proto  = "tcp"
	addr   = "172.16.33.54:6380"
	active = 20
	idle   = 10
	dialTimeout  = "50ms"
	readTimeout  = "100ms"
	writeTimeout = "100ms"
	idleTimeout  = "80s"
	expire = "2h"

[memcache]
	[memcache.operator]
	name   = "app-show/archive"
	proto  = "tcp"
	addr   = "172.22.33.117:11214"
	active = 50
	idle   = 10
	dialTimeout  = "50ms"
	readTimeout  = "100ms"
	writeTimeout = "100ms"
	idleTimeout  = "80s"
	expire = "1s"

[reddot]
    starttime="2018-02-26 00:00:00"
    endtime="2028-02-26 00:00:00"

[unicom]
    keyExpired = "1s"
    flowProduct = [
        {spid="979",desc="15元包",type=4},
        {spid="1032",desc="20元包",type=4},
        {id="90987322",spid="",desc="s10免流包",type=5,tag="s10",way="ip"},
        ]
    cardProduct = [
        {id="90157638",spid="10019",desc="22卡",type=1},
        {id="90157639",spid="10020",desc="33卡",type=2},
        {id="90157799",spid="10021",desc="小电视卡",type=3},
        ]
    [unicom.exchangeLimit]
        phoneWhitelist = []

[telecom]
    keyExpired = "5m"
    payKeyExpired = "5m"
    smsTemplate = "app-wall-01"
    smsMsgTemplate = "app-wall-04"
    smsFlowTemplate = "app-wall-03"
    smsOrderTemplateOK = "app-wall-02"
    flowPercentage = 10
    cardProduct = [
        {id = "5000003201100285",desc = "真香卡",type=1},
        {id = "5000003201100288",desc = "真香卡",type=1},
        {id = "5000003201100284",desc = "真实卡",type=2},
        {id = "5000003201100287",desc = "真实卡",type=2},
        {id = "5000003201100286",desc = "真爱卡",type=3},
        {id = "qnyp",desc = "青年一派卡",type=3},
        ]
    [telecom.area]
    area=["CN50","CN44","CN31","CN43","CN14","CN13","CN45","CN35","CN37","CN46","CN64","CN23","CN62","CN63","CN15","CN21","CN41","CN36","CN12","CN42","CN53"]
    # 重庆 CN50
    # 广东 CN44
    # 上海 CN31
    # 湖南 CN43
    # 山西 CN14
    # 河北 CN13
    # 广西 CN45
    # 福建 CN35
    # 山东 CN37
    # 海南 CN46
    # 宁夏 CN64
    # 黑龙江 CN23
    # 甘肃 CN62
    # 青海 CN63
    # 内蒙 CN15
    # 辽宁 CN21
    # 河南 CN41
    # 江西 CN36
    # 天津 CN12
    # 湖北 CN42
    # 云南 CN53

[mobile]
    flowProduct = [
        {id = "100000000028",desc = "哔哩哔哩9元话费3GB流量包"},
        {id = "100000000030",desc = "哔哩哔哩24元话费30GB流量包"},
        {id = "100000001142",desc = "15GB哔哩哔哩定向流量包"},
        {id = "100000001143",desc = "15GB哔哩哔哩定向流量包"},
        {id = "100000001144",desc = "15GB哔哩哔哩定向流量包"},
        {id = "100000001145",desc = "15GB哔哩哔哩定向流量包"},
        {id = "100000001146",desc = "15GB哔哩哔哩定向流量包"},
        {id = "100000001199",desc = "哔哩哔哩折扣流量包"},
        {id = "100000001278",desc = "哔哩哔哩随心看会员-折扣包"},
        {id = "100000001277",desc = "哔哩哔哩随心看会员"},
        {id = "100000001272",desc = "移动免流包"},
        {id = "100000001271",desc = "移动免流包"},
        {id = "",desc = "s10免流包",tag = "s10"},
        ]
    cardProduct = [
        {id = "100000001178",desc = "花卡"},
        {id = "300000000450",desc = "花卡"},
        ]

[rule]
    cu = [
            {m = "break",tf = false,p = "^(POST|PUT)@|.*\\.bilibili\\.com/"},
            {m = "break",tf = true,p = "^GET@(([0-9]{1,3}\\.){3}[0-9]{1,3}|((proxy|upcdn|upos|bfs|acache)-tf-|cn-).*\\.(acgvideo|bilivideo)\\.com)/|/live-bvc/"},
            {m = "replace",tf = true,p = "^GET@(i|s)[0-9]\\.hdslb\\.com/",a = "bfs-tf-all-js.bilivideo.com"},
            {m = "replace",tf = true,p = "^GET@upos-.*(u\\.acgvideo|mirror.*\\.bilivideo)\\.com/",a = "upos-tf-all-js.bilivideo.com"},
            {m = "proxy",tf = true,p = "^GET@(([\\w-]+\\.)*(bilibili|acgvideo|bilivideo|acg|hdslb|biligame|bilibiliyoo|im9|b23|missevan)\\.(com|tv|cn|co|net))/",a = "proxy-tf-all-ws.bilivideo.com"},
        ]
    ct = [
            {m = "break",tf = false,p = "^(POST|PUT)@|.*\\.bilibili\\.com/"},
            {m = "break",tf = true,p = "^GET@(([0-9]{1,3}\\.){3}[0-9]{1,3}|((proxy|upcdn|upos|bfs|acache)-tf-|cn-).*\\.(acgvideo|bilivideo)\\.com)/|/live-bvc/"},
            {m = "replace",tf = true,p = "^GET@(i|s)[0-9]\\.hdslb\\.com/",a = "bfs-tf-all-js.bilivideo.com"},
            {m = "replace",tf = true,p = "^GET@upos-.*(u\\.acgvideo|mirror.*\\.bilivideo)\\.com/",a = "upos-tf-all-js.bilivideo.com"},
            {m = "proxy",tf = true,p = "^GET@(([\\w-]+\\.)*(bilibili|acgvideo|bilivideo|acg|hdslb|biligame|bilibiliyoo|im9|b23|missevan)\\.(com|tv|cn|co|net))/",a = "proxy-tf-all-ws.bilivideo.com"},
        ]
    cm = [
            {m = "break",tf = false,p = "^(POST|PUT)@|.*\\.bilibili\\.com/"},
            {m = "break",tf = true,p = "^GET@(([0-9]{1,3}\\.){3}[0-9]{1,3}|((proxy|upcdn|upos|bfs|acache)-tf-|cn-).*\\.(acgvideo|bilivideo)\\.com)/|/live-bvc/"},
            {m = "replace",tf = true,p = "^GET@(i|s)[0-9]\\.hdslb\\.com/",a = "bfs-tf-all-js.bilivideo.com"},
            {m = "replace",tf = true,p = "^GET@upos-.*(u\\.acgvideo|mirror.*\\.bilivideo)\\.com/",a = "upos-tf-all-js.bilivideo.com"},
            {m = "proxy",tf = true,p = "^GET@(([\\w-]+\\.)*(bilibili|acgvideo|bilivideo|acg|hdslb|biligame|bilibiliyoo|im9|b23|missevan)\\.(com|tv|cn|co|net))/",a = "proxy-tf-all-ws.bilivideo.com"},
        ]

[accountVIP]
    "7⽇大会员" = {batchID = 27,appKey = "0e9b9fcce22daaf1",days = 7}
    "1个月大会员" = {batchID = 841,appKey = "PrFokWmXVSdaWkRz",days = 30}
