DROP TABLE `bnj_ar_draw_log_00`;
DROP TABLE `bnj_ar_draw_log_01`;
DROP TABLE `bnj_ar_draw_log_02`;
DROP TABLE `bnj_ar_draw_log_03`;
DROP TABLE `bnj_ar_draw_log_04`;
DROP TABLE `bnj_ar_draw_log_05`;
DROP TABLE `bnj_ar_draw_log_06`;
DROP TABLE `bnj_ar_draw_log_07`;
DROP TABLE `bnj_ar_draw_log_08`;
DROP TABLE `bnj_ar_draw_log_09`;
DROP TABLE `bnj_ar_draw_log_10`;
DROP TABLE `bnj_ar_draw_log_11`;
DROP TABLE `bnj_ar_draw_log_12`;
DROP TABLE `bnj_ar_draw_log_13`;
DROP TABLE `bnj_ar_draw_log_14`;
DROP TABLE `bnj_ar_draw_log_15`;
DROP TABLE `bnj_ar_draw_log_16`;
DROP TABLE `bnj_ar_draw_log_17`;
DROP TABLE `bnj_ar_draw_log_18`;
DROP TABLE `bnj_ar_draw_log_19`;
DROP TABLE `bnj_ar_draw_log_20`;
DROP TABLE `bnj_ar_draw_log_21`;
DROP TABLE `bnj_ar_draw_log_22`;
DROP TABLE `bnj_ar_draw_log_23`;
DROP TABLE `bnj_ar_draw_log_24`;
DROP TABLE `bnj_ar_draw_log_25`;
DROP TABLE `bnj_ar_draw_log_26`;
DROP TABLE `bnj_ar_draw_log_27`;
DROP TABLE `bnj_ar_draw_log_28`;
DROP TABLE `bnj_ar_draw_log_29`;
DROP TABLE `bnj_ar_draw_log_30`;
DROP TABLE `bnj_ar_draw_log_31`;
DROP TABLE `bnj_ar_draw_log_32`;
DROP TABLE `bnj_ar_draw_log_33`;
DROP TABLE `bnj_ar_draw_log_34`;
DROP TABLE `bnj_ar_draw_log_35`;
DROP TABLE `bnj_ar_draw_log_36`;
DROP TABLE `bnj_ar_draw_log_37`;
DROP TABLE `bnj_ar_draw_log_38`;
DROP TABLE `bnj_ar_draw_log_39`;
DROP TABLE `bnj_ar_draw_log_40`;
DROP TABLE `bnj_ar_draw_log_41`;
DROP TABLE `bnj_ar_draw_log_42`;
DROP TABLE `bnj_ar_draw_log_43`;
DROP TABLE `bnj_ar_draw_log_44`;
DROP TABLE `bnj_ar_draw_log_45`;
DROP TABLE `bnj_ar_draw_log_46`;
DROP TABLE `bnj_ar_draw_log_47`;
DROP TABLE `bnj_ar_draw_log_48`;
DROP TABLE `bnj_ar_draw_log_49`;
DROP TABLE `bnj_ar_draw_log_50`;
DROP TABLE `bnj_ar_draw_log_51`;
DROP TABLE `bnj_ar_draw_log_52`;
DROP TABLE `bnj_ar_draw_log_53`;
DROP TABLE `bnj_ar_draw_log_54`;
DROP TABLE `bnj_ar_draw_log_55`;
DROP TABLE `bnj_ar_draw_log_56`;
DROP TABLE `bnj_ar_draw_log_57`;
DROP TABLE `bnj_ar_draw_log_58`;
DROP TABLE `bnj_ar_draw_log_59`;
DROP TABLE `bnj_ar_draw_log_60`;
DROP TABLE `bnj_ar_draw_log_61`;
DROP TABLE `bnj_ar_draw_log_62`;
DROP TABLE `bnj_ar_draw_log_63`;
DROP TABLE `bnj_ar_draw_log_64`;
DROP TABLE `bnj_ar_draw_log_65`;
DROP TABLE `bnj_ar_draw_log_66`;
DROP TABLE `bnj_ar_draw_log_67`;
DROP TABLE `bnj_ar_draw_log_68`;
DROP TABLE `bnj_ar_draw_log_69`;
DROP TABLE `bnj_ar_draw_log_70`;
DROP TABLE `bnj_ar_draw_log_71`;
DROP TABLE `bnj_ar_draw_log_72`;
DROP TABLE `bnj_ar_draw_log_73`;
DROP TABLE `bnj_ar_draw_log_74`;
DROP TABLE `bnj_ar_draw_log_75`;
DROP TABLE `bnj_ar_draw_log_76`;
DROP TABLE `bnj_ar_draw_log_77`;
DROP TABLE `bnj_ar_draw_log_78`;
DROP TABLE `bnj_ar_draw_log_79`;
DROP TABLE `bnj_ar_draw_log_80`;
DROP TABLE `bnj_ar_draw_log_81`;
DROP TABLE `bnj_ar_draw_log_82`;
DROP TABLE `bnj_ar_draw_log_83`;
DROP TABLE `bnj_ar_draw_log_84`;
DROP TABLE `bnj_ar_draw_log_85`;
DROP TABLE `bnj_ar_draw_log_86`;
DROP TABLE `bnj_ar_draw_log_87`;
DROP TABLE `bnj_ar_draw_log_88`;
DROP TABLE `bnj_ar_draw_log_89`;
DROP TABLE `bnj_ar_draw_log_90`;
DROP TABLE `bnj_ar_draw_log_91`;
DROP TABLE `bnj_ar_draw_log_92`;
DROP TABLE `bnj_ar_draw_log_93`;
DROP TABLE `bnj_ar_draw_log_94`;
DROP TABLE `bnj_ar_draw_log_95`;
DROP TABLE `bnj_ar_draw_log_96`;
DROP TABLE `bnj_ar_draw_log_97`;
DROP TABLE `bnj_ar_draw_log_98`;
DROP TABLE `bnj_ar_draw_log_99`;

CREATE TABLE `bnj_ar_draw_log_00` (
    `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    `mid` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '用户id',
    `rec_unix` varchar(32) NOT NULL DEFAULT '' COMMENT '落库前服务器微秒',
    `no` tinyint(4) UNSIGNED NOT NULL DEFAULT 1 COMMENT '批量插入的序号',
    `received` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '0: 未抽奖 1: 已抽奖 2：已发放',
    `reward` TEXT NOT NULL DEFAULT '' COMMENT '中奖信息',
    `ctime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `mtime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    PRIMARY KEY (`id`),
    KEY `ix_mid_unix_no` (`mid`, `rec_unix`, `no`),
    KEY `ix_mtime` (`mtime`)
) ENGINE = InnoDB CHARSET = utf8 COMMENT '拜年纪直播间AR奖券抽奖明细';

CREATE TABLE `bnj_ar_draw_log_01` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_02` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_03` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_04` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_05` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_06` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_07` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_08` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_09` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_10` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_11` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_12` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_13` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_14` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_15` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_16` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_17` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_18` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_19` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_20` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_21` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_22` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_23` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_24` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_25` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_26` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_27` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_28` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_29` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_30` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_31` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_32` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_33` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_34` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_35` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_36` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_37` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_38` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_39` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_40` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_41` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_42` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_43` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_44` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_45` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_46` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_47` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_48` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_49` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_50` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_51` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_52` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_53` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_54` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_55` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_56` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_57` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_58` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_59` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_60` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_61` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_62` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_63` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_64` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_65` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_66` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_67` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_68` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_69` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_70` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_71` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_72` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_73` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_74` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_75` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_76` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_77` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_78` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_79` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_80` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_81` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_82` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_83` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_84` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_85` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_86` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_87` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_88` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_89` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_90` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_91` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_92` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_93` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_94` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_95` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_96` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_97` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_98` LIKE `bnj_ar_draw_log_00`;
CREATE TABLE `bnj_ar_draw_log_99` LIKE `bnj_ar_draw_log_00`;
