[HTTPServer]
	addr = "0.0.0.0:6881"
	timeout = "1s"
[rule]
    openDynamic = true
    upSenderUid = 26366366
    regularExpire = "36h"
    upActOpen = true
    upFansLimit = 10000


[log]
    dir = "/data/log/native-page-interface/"

[httpClient]
    key = "33ac033ce123e590"
    secret = "0b2847315d32989a248294e350ac3ede"
    dial = "500ms"
    timeout = "2s"
    keepAlive = "60s"

[httpDynamic]
    key = "33ac033ce123e590"
    secret = "0b2847315d32989a248294e350ac3ede"
    dial = "500ms"
    timeout = "300ms"
    keepAlive = "60s"

[httpBusiness]
    key = "topic-query"
    secret = "83e8ef09b4dd1fcf8b8f99aa065b2d3b"
    dial = "200ms"
    timeout = "2s"
    keepAlive = "60s"

[redis]
    name = "native-page-job"
    proto = "tcp"
    addr = "127.0.0.1:32768"
    idle = 10
    active = 10
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "10s"

[cron]
    OnlinePages = "@every 3s"

[dataBus]
    [dataBus.nativePub]
        key = "9765cdac5894f2ba"
        secret = "f4237d712c3ed1e7fab0137b81418b14"
        group = "ActivityNative-MainWebSvr-P"
        topic = "ActivityNative-T"
        action = "pub"
        dialTimeout = "1s"
        readTimeout = "1s"
        writeTimeout = "1s"

[mysql]
    [mysql.like]
    addr = "172.16.33.205:3308"
    dsn = "test:test@tcp(172.16.33.205:3308)/bilibili_lottery?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 5
    idle = 2
    idleTimeout ="4h"
    queryTimeout = "1s"
    execTimeout = "1s"
    tranTimeout = "2s"
    [mysql.like.breaker]
    window  ="3s"
    sleep   ="100ms"
    bucket  = 10
    ratio   = 0.5

[host]
    apiCo   = "http://api.bilibili.co"
    dynamic = "http://uat-api.vc.bilibili.co"
    business = "http://b.bilibili.com"
    gameCo  = "http://game-center-open-api.bilibili.co"
    showCo = "http://show.bilibili.co"
    mangaCo = "http://uat-manga.bilibili.co/"

[NativePage]
    whiteListByMidExpire = 432000
    whiteListByMidNullExpire = 3600

[limiter]
    Disable = false
    Preflight = false
    [[limiter.Methods]]
        path = "/x/activity/s10/coin/award"
        Rule = "total"


[QuotaConf]
  [[QuotaConf.Methods]]
     path = "/natpage.interface.service.v1.NaPage/NatInfoFromForeign"
     rule = "caller"

[HTTPGameCo]
key    = "EeOpM531WqQnBvu4"
secret = "gHtKtXTHZJDqGP1tg9ORFs0YWV3kW12V"
dial      = "100ms"
timeout   = "500ms"
keepAlive = "60s"

[HTTPMangaCo]
key    = "EeOpM531WqQnBvu4"
secret = "gHtKtXTHZJDqGP1tg9ORFs0YWV3kW12V"
dial      = "100ms"
timeout   = "500ms"
keepAlive = "60s"

[HTTPShowCo]
key    = "EeOpM531WqQnBvu4"
secret = "gHtKtXTHZJDqGP1tg9ORFs0YWV3kW12V"
dial      = "100ms"
timeout   = "500ms"
keepAlive = "60s"