
#  toml config

[rule]
    docLimit = 102400

[mysql]
addr   = "172.22.34.101:3306"
dsn    = "test_3306:UJPZaGKjpb2ylFx3HNhmLuwOYft4MCAi@tcp(172.22.34.101:3306)/bilibili_kvo?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
active = 5
idle   = 2
idleTimeout  = "4h"
queryTimeout = "200ms"
execTimeout  = "200ms"
tranTimeout  = "200ms"
[mysql.breaker]
window = "1s"
sleep = "100ms"
bucket = 10
ratio = 0.5
request = 100

[xlog]
#dir = "/data/log/kvo/"
[xlog.agent]
family = "kvo"
taskID = "000069"
proto = "unixgram"
addr = "/var/run/lancer/collector.sock"
chan = 10240

[tracer]
family = "platform/kvo"
proto = "unixgram"
addr = "/var/run/dapper-collect/dapper-collect.sock"

[bm]
addr = "0.0.0.0:6691"
timeout = "1s"

[memcache]
expire = "720h"
    [memcache.kvo]
    name = "kvo"
    proto = "tcp"
    addr = "127.0.0.1:20110"
    idle = 10
    active = 10
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "80s"

[redis]
    expire = "30m"
    increxpire = "15m"
    [redis.redis]
    name = "kvo"
	proto = "tcp"
	addr = "172.22.33.31:6878"
	idle = 1024
	active = 6000
	dialTimeout = "1s"
	readTimeout = "1s"
	writeTimeout = "1s"
	idleTimeout = "10s"


[taskpub]
    key = "170e302355453683"
    secret= "3d0e8db7bed0503949e545a469789279"
     group= "DMplayerconfig-MainCommunity-P"
     topic= "DMplayerconfig-T"
    action="pub"
    name = "dm2"
    proto = "tcp"
    addr = "172.22.33.174:6205"
    idle = 1
    active = 10
    dialTimeout = "1s"
    readTimeout = "60s"
    writeTimeout = "1s"
    idleTimeout = "10s"

[buvidtaskpub]
    key = "170e302355453683"
    secret= "3d0e8db7bed0503949e545a469789279"
    group= "Kvo-MainCommunity-P"
    topic= "Kvo-T"
    action="pub"
    name = "dm2"
    proto = "tcp"
    addr = "172.22.33.174:6205"
    idle = 1
    active = 10
    dialTimeout = "1s"
    readTimeout = "60s"
    writeTimeout = "1s"
    idleTimeout = "10s"

[localcache]
    max = 256
    bucketSize = 10


[Taishan]
    Table = "kvo_document"
    Token = "kvo_document"

[infocLogStream]
    path="/data/log/recordio/"
    name="data.log"
    chan=8024
    buffer=10
    rotated=true