// Code generated by kratos tool mcgen. DO NOT EDIT.

/*
  Package kfc is a generated mc cache package.
  It is generated from:
  type _mc interface {
		// mc: -key=kfcKey
		CacheKfcCoupon(c context.Context, id int64) (*kfc.BnjKfcCoupon, error)
		// mc: -key=kfcKey -expire=d.mcKfcExpire -encode=pb
		AddCacheKfcCoupon(c context.Context, id int64, val *kfc.BnjKfcCoupon) error
		// mc: -key=kfcKey
		DelCacheKfcCoupon(c context.Context, id int64) error
		// mc: -key=kfcCodeKey
		CacheKfcCode(c context.Context, code string) (int64, error)
		// mc: -key=kfcCodeKey -expire=d.mcKfcCodeExpire -encode=raw
		AddCacheKfcCode(c context.Context, code string, val int64) error
	}
*/

package kfc

import (
	"context"
	"fmt"
	"strconv"

	"go-common/library/cache/memcache"
	"go-common/library/log"
	"go-gateway/app/web-svr/activity/interface/model/kfc"
)

var _ _mc

// CacheKfcCoupon get data from mc
func (d *Dao) CacheKfcCoupon(c context.Context, id int64) (res *kfc.BnjKfcCoupon, err error) {
	key := kfcKey(id)
	res = &kfc.BnjKfcCoupon{}
	if err = d.mc.Get(c, key).Scan(res); err != nil {
		res = nil
		if err == memcache.ErrNotFound {
			err = nil
		}
	}
	if err != nil {
		log.Errorv(c, log.KV("CacheKfcCoupon", fmt.Sprintf("%+v", err)), log.KV("key", key))
		return
	}
	return
}

// AddCacheKfcCoupon Set data to mc
func (d *Dao) AddCacheKfcCoupon(c context.Context, id int64, val *kfc.BnjKfcCoupon) (err error) {
	if val == nil {
		return
	}
	key := kfcKey(id)
	item := &memcache.Item{Key: key, Object: val, Expiration: d.mcKfcExpire, Flags: memcache.FlagProtobuf}
	if err = d.mc.Set(c, item); err != nil {
		log.Errorv(c, log.KV("AddCacheKfcCoupon", fmt.Sprintf("%+v", err)), log.KV("key", key))
		return
	}
	return
}

// DelCacheKfcCoupon delete data from mc
func (d *Dao) DelCacheKfcCoupon(c context.Context, id int64) (err error) {
	key := kfcKey(id)
	if err = d.mc.Delete(c, key); err != nil {
		if err == memcache.ErrNotFound {
			err = nil
			return
		}
		log.Errorv(c, log.KV("DelCacheKfcCoupon", fmt.Sprintf("%+v", err)), log.KV("key", key))
		return
	}
	return
}

// CacheKfcCode get data from mc
func (d *Dao) CacheKfcCode(c context.Context, id string) (res int64, err error) {
	key := kfcCodeKey(id)
	var v string
	err = d.mc.Get(c, key).Scan(&v)
	if err != nil {
		if err == memcache.ErrNotFound {
			err = nil
			return
		}
		log.Errorv(c, log.KV("CacheKfcCode", fmt.Sprintf("%+v", err)), log.KV("key", key))
		return
	}
	r, err := strconv.ParseInt(v, 10, 64)
	if err != nil {
		log.Errorv(c, log.KV("CacheKfcCode", fmt.Sprintf("%+v", err)), log.KV("key", key))
		return
	}
	res = int64(r)
	return
}

// AddCacheKfcCode Set data to mc
func (d *Dao) AddCacheKfcCode(c context.Context, id string, val int64) (err error) {
	key := kfcCodeKey(id)
	bs := []byte(strconv.FormatInt(int64(val), 10))
	item := &memcache.Item{Key: key, Value: bs, Expiration: d.mcKfcCodeExpire, Flags: memcache.FlagRAW}
	if err = d.mc.Set(c, item); err != nil {
		log.Errorv(c, log.KV("AddCacheKfcCode", fmt.Sprintf("%+v", err)), log.KV("key", key))
		return
	}
	return
}
