# This is a TOML document. Boom.

version = "1.0.1"
user    = "nobody"
pid     = "/tmp/app-resource.pid"
dir     = "./"
perf    = "127.0.0.1:6850"
checkFile = "/data/www/app-resource.html"
family = "app-resource"
trace   = false
debug   = true

env     = "dev"
resourceLog = ""
tick    = "30s"
quickerTick    = "1m"

modLowPool = ["MainSiteBW"]

[identify]
    WhiteAccessKey = ""
    WhiteMid = 0
    [identify.app]
    key = "6a29f8ed87407c11"
    secret = "d3c5a85f5b895a03735b5d20a273bc57"
    [identify.memcache]
    name = "go-business/identify"
    proto = "tcp"
    addr = "172.16.33.54:11211"
    active = 5
    idle = 10
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "80s"
    [identify.host]
    auth = "http://passport.bilibili.com"
    secret = "http://open.bilibili.com"
    [identify.authHTTPClient]
    dial = "1s"
    timeout = "1s"
    keepAlive = "60s"
    timer = 1000
    [identify.secretHTTPClient]
    dial = "1s"
    timeout = "1s"
    keepAlive = "60s"
    timer = 1000

[tracer]
proto = "udp"
addr  = "172.16.33.46:5140"
tag   = "platform/app-resource"

[xlog]
dir = "/data/log/app-resource/"
    [xlog.elk]
    project  = "app-resource"
    addr     = "172.18.20.17:8520"
    chanSize = 10240
    [xlog.syslog]
    project  = "app-resource"
    chanSize = 10240

[app]
key    = "e7482d29be4a95b8"
secret = "9e803791cdef756e75faee68e12b7442"

[multiHttp]
    [multiHttp.outer]
    addrs     = ["0.0.0.0:6851"]
    maxListen = 100
    [multiHttp.local]
    addrs     = ["0.0.0.0:6853"]
    maxListen = 100

[ecode]
    domain = "172.16.33.248:6401"
    all = "1h"
    diff = "5m"
    [ecode.clientconfig]
        dial      = "2000ms"
        timeout   = "2s"
        keepAlive = "10s"
        timer     = 128
        [ecode.clientconfig.breaker]
            window  ="3s"
            sleep   ="100ms"
            bucket  = 10
            ratio   = 0.5
            request = 100
    [ecode.app]
         key = "test"
         secret = "e6c4c252dc7e3d8a90805eecd7c73396"

[mysql]
[mysql.show]
addr = "172.16.0.148:3306"
dsn = "test:test@tcp(172.16.0.148:3306)/bilibili_show?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8mb4,utf8"
active = 5
idle = 2

[tf]
rule = "{         \"cu\": [         {             \"m\": \"break\",             \"tf\": false,             \"p\": \"^(POST|PUT)@|.*\\\\.bilibili\\\\.com/\"         },         {             \"m\": \"break\",             \"tf\": true,             \"p\": \"^GET@(([0-9]{1,3}\\\\.){3}[0-9]{1,3}|((proxy|upcdn|upos|bfs|acache)-tf-|cn-).*\\\\.(acgvideo|bilivideo)\\\\.com)/|/live-bvc/\"         },         {             \"tf\": true,             \"m\": \"replace\",             \"a\": \"bfs-tf-all-js.bilivideo.com\",             \"p\": \"^GET@(i|s)[0-9]\\\\.hdslb\\\\.com/\"         },         {             \"tf\": true,             \"m\": \"replace\",             \"a\": \"upos-tf-all-js.bilivideo.com\",             \"p\": \"^GET@upos-.*(u\\\\.acgvideo|mirror.*\\\\.bilivideo)\\\\.com/\"         },         {             \"tf\": true,             \"m\": \"proxy\",             \"a\": \"proxy-tf-all-ws.bilivideo.com\",             \"p\": \"^GET@(([\\\\w-]+\\\\.)*(bilibili|acgvideo|bilivideo|acg|hdslb|biligame|bilibiliyoo|im9|b23|missevan)\\\\.(com|tv|cn|co|net))/\"         }     ],     \"ct\": [         {             \"m\": \"break\",             \"tf\": false,             \"p\": \"^(POST|PUT)@|.*\\\\.bilibili\\\\.com/\"         },         {             \"m\": \"break\",             \"tf\": true,             \"p\": \"^GET@(([0-9]{1,3}\\\\.){3}[0-9]{1,3}|((proxy|upcdn|upos|bfs|acache)-tf-|cn-).*\\\\.(acgvideo|bilivideo)\\\\.com)/|/live-bvc/\"         },         {             \"tf\": true,             \"m\": \"replace\",             \"a\": \"bfs-tf-all-js.bilivideo.com\",             \"p\": \"^GET@(i|s)[0-9]\\\\.hdslb\\\\.com/\"         },         {             \"tf\": true,             \"m\": \"replace\",             \"a\": \"upos-tf-all-js.bilivideo.com\",             \"p\": \"^GET@upos-.*(u\\\\.acgvideo|mirror.*\\\\.bilivideo)\\\\.com/\"         },         {             \"tf\": true,             \"m\": \"proxy\",             \"a\": \"proxy-tf-all-ws.bilivideo.com\",             \"p\": \"^GET@(([\\\\w-]+\\\\.)*(bilibili|acgvideo|bilivideo|acg|hdslb|biligame|bilibiliyoo|im9|b23|missevan)\\\\.(com|tv|cn|co|net))/\"         }     ],     \"cm\": [         {             \"m\": \"break\",             \"tf\": false,             \"p\": \"^(POST|PUT)@|.*\\\\.bilibili\\\\.com/\"         },         {             \"m\": \"break\",             \"tf\": true,             \"p\": \"^GET@(([0-9]{1,3}\\\\.){3}[0-9]{1,3}|((proxy|upcdn|upos|bfs|acache)-tf-|cn-).*\\\\.(acgvideo|bilivideo)\\\\.com)/|/live-bvc/\"         },         {             \"tf\": true,             \"m\": \"replace\",             \"a\": \"bfs-tf-all-js.bilivideo.com\",             \"p\": \"^GET@(i|s)[0-9]\\\\.hdslb\\\\.com/\"         },         {             \"tf\": true,             \"m\": \"replace\",             \"a\": \"upos-tf-all-js.bilivideo.com\",             \"p\": \"^GET@upos-.*(u\\\\.acgvideo|mirror.*\\\\.bilivideo)\\\\.com/\"         },         {             \"tf\": true,             \"m\": \"proxy\",             \"a\": \"proxy-tf-all-ws.bilivideo.com\",             \"p\": \"^GET@(([\\\\w-]+\\\\.)*(bilibili|acgvideo|bilivideo|acg|hdslb|biligame|bilibiliyoo|im9|b23|missevan)\\\\.(com|tv|cn|co|net))/\"         }     ],     \"version\": 9 }"

[RegistrationDateEventConfig]
LogoURL = "http://i0.hdslb.com/bfs/archive/1b1a8a4fc78a3b1b2992402ebdc19808b9d251ed.png"
ShowTimes = 3
[RegistrationDateEventConfig.Normal]
ImageURL = ""
[RegistrationDateEventConfig.Normal.AccountCard]
Enable = true
MaxWidth = "320px"
PaddingTop = "50%"
[RegistrationDateEventConfig.Normal.Greeting]
Enable = true
MaxWidth = "320px"
PaddingTop = "3%"
Text = "<font color=\"#000000\" >注册<strong><font color=\"#ff5377\" >{{.passYears}}周年</font></strong>快乐！</font>"
[RegistrationDateEventConfig.Normal.Text]
Enable = true
MaxWidth = "320px"
PaddingTop = "3%"
Text = "<font color=\"#000000\" ><font color=\"#ff5377\" >{{.joinYear}}年{{.joinMonth}}月{{.joinDay}}日</font>，我们初次遇见<font color=\"#ff5377\" >{{.passDays}}</font>个日夜，相伴走过了许多风景下一个冬夏，也请多指教呀电波相连，我们的故事永不完结~</font>"
[RegistrationDateEventConfig.Full]
ImageURL = ""
[RegistrationDateEventConfig.Full.AccountCard]
Enable = true
MaxWidth = "320px"
PaddingTop = "50%"
[RegistrationDateEventConfig.Full.Greeting]
Enable = true
MaxWidth = "320px"
PaddingTop = "3%"
Text = "<font color=\"#000000\" >注册<strong><font color=\"#ff5377\" >{{.passYears}}周年</font></strong>快乐！</font>"
[RegistrationDateEventConfig.Full.Text]
Enable = true
MaxWidth = "320px"
PaddingTop = "3%"
Text = "<font color=\"#000000\" ><font color=\"#ff5377\" >{{.joinYear}}年{{.joinMonth}}月{{.joinDay}}日</font>，我们初次遇见<font color=\"#ff5377\" >{{.passDays}}</font>个日夜，相伴走过了许多风景下一个冬夏，也请多指教呀电波相连，我们的故事永不完结~</font>"
[RegistrationDateEventConfig.Pad]
ImageURL = ""
[RegistrationDateEventConfig.Pad.AccountCard]
Enable = true
MaxWidth = "320px"
PaddingTop = "50%"
[RegistrationDateEventConfig.Pad.Greeting]
Enable = true
MaxWidth = "320px"
PaddingTop = "3%"
Text = "<font color=\"#000000\" >注册<strong><font color=\"#ff5377\" >{{.passYears}}周年</font></strong>快乐！</font>"
[RegistrationDateEventConfig.Pad.Text]
Enable = true
MaxWidth = "320px"
PaddingTop = "3%"
Text = "<font color=\"#000000\" ><font color=\"#ff5377\" >{{.joinYear}}年{{.joinMonth}}月{{.joinDay}}日</font>，我们初次遇见<font color=\"#ff5377\" >{{.passDays}}</font>个日夜，相伴走过了许多风景下一个冬夏，也请多指教呀电波相连，我们的故事永不完结~</font>"
