[show]
    addr = "172.16.33.205:3308"
    dsn = "test:test@tcp(172.16.33.205:3308)/bilibili_show?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 2
    idle = 1
    queryTimeout = "1s"
    execTimeout = "1s"
    tranTimeout = "1s"