[log]
#dir = "/data/log/space-admin/"
stdout = true



[orm]
dsn = "space:hC0WPEpsaQhOpLqZaWKbc6fNcRdMiouC@tcp(172.22.34.101:3309)/space?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
#dsn = "root:Dongdong@!21@tcp(127.0.0.1:3306)/test?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
active = 20
idle = 5
idleTimeout = "4h"

[BM]
    addr = "0.0.0.0:8001"
    maxListen = 1000
    timeout = "10m"
    readTimeout = "10m"
    writeTimeout = "10m"

[HTTPClient]
    key = "b1014d7c339a5649"
    secret = "75b74b612aa792b112e6504cae44c319"
    dial      = "50ms"
    timeout   = "1s"
    keepAlive = "60s"

[host]
    message = "http://uat-message.bilibili.co"
    api = "http://uat-api.bilibili.co"
    manager = "http://uat-manager.bilibili.co"
    vip = "http://uat-vip.bilibili.co"
    space = "http://uat-space.bilibili.com"
    bfs= "http://uat-i0.hdslb.com"

[permit]
    managerHost = "http://uat-manager.bilibili.co"
    dashboardHost = "http://dashboard-mng.bilibili.co"
    dashboardCaller = "manager-go"
    [permit.DsHTTPClient]
    key = "manager-go"
    secret = "949bbb2dd3178252638c2407578bc7ad"
    dial = "1s"
    timeout = "1s"
    keepAlive = "60s"
    [permit.MaHTTPClient]
    key = "f6433799dbd88751"
    secret = "36f8ddb1806207fe07013ab6a77a3935"
    dial = "1s"
    timeout = "1s"
    keepAlive = "60s"
    [permit.MaHTTPClient.breaker]
    window  = "3s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100
    [permit.session]
    sessionIDLength = 32
    cookieLifeTime = 1800
    cookieName = "mng-go"
    domain = ".bilibili.co"
    [permit.session.Memcache]
    name = "go-business/auth"
    proto = "tcp"
    addr = "127.0.0.1:11211"
    active = 10
    idle = 5
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "80s"