[mysql]
    [mysql.bnj]
    addr = "172.22.34.101:3306"
    dsn = "test:pqAgqRbLBa7afOAQ47IBlqvJcOGI9YNd@tcp(172.16.33.205:3308)/bilibili_lottery?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 5
    idle = 2
    idleTimeout ="4h"
    queryTimeout = "5000ms"
    execTimeout = "5000ms"
    tranTimeout = "5000ms"
    [mysql.bnj.breaker]
    window  ="3s"
    sleep   ="100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100
    [mysql.like]
    addr = "172.22.34.101:3306"
    dsn = "test:pqAgqRbLBa7afOAQ47IBlqvJcOGI9YNd@tcp(172.16.33.205:3308)/bilibili_lottery?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 5
    idle = 2
    idleTimeout ="4h"
    queryTimeout = "5000ms"
    execTimeout = "5000ms"
    tranTimeout = "5000ms"
    [mysql.like.breaker]
    window  ="3s"
    sleep   ="100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100
    [mysql.act]
    addr = "172.22.34.101:3306"
    dsn = "test:pqAgqRbLBa7afOAQ47IBlqvJcOGI9YNd@tcp(172.16.33.205:3308)/bilibili_lottery?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 5
    idle = 2
    idleTimeout ="4h"
    queryTimeout = "5000ms"
    execTimeout = "5000ms"
    tranTimeout = "5000ms"
    [mysql.act.breaker]
    window  ="3s"
    sleep   ="100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100

[TiDB]
    addr = "uat-tidb-4000.testdb.bilibili.co:4000"
    dsn = "main_lottery:RWXcNcw1X43S1K1nvB51x7iNjMMjP0ba@tcp(10.221.34.182:4000)/main_lottery?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 5
    idle = 2
    idleTimeout ="4h"
    queryTimeout = "1s"
    execTimeout = "1s"
    tranTimeout = "2s"
    [TiDB.breaker]
    window  ="3s"
    sleep   ="100ms"
    bucket  = 10
    ratio   = 0.5


[hbase]
master = ""
meta = ""
dialTimeout = "100ms"
readTimeout = "100ms"
readsTimeout = "100ms"
writeTimeout = "100ms"
writesTimeout = "100ms"
    [hbase.zookeeper]
    root = ""
     addrs = ["172.18.33.75:2181" ]
    timeout = "100ms"

[S10MySQL]
    addr = "172.22.34.101:3306"
    dsn = "test:pqAgqRbLBa7afOAQ47IBlqvJcOGI9YNd@tcp(172.16.33.205:3308)/bilibili_lottery?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 5
    idle = 2
    idleTimeout ="4h"
    queryTimeout = "500ms"
    execTimeout = "500ms"
    tranTimeout = "500ms"
    [S10MySQL.breaker]
        window  ="3s"
        sleep   ="100ms"
        bucket  = 10
        ratio   = 0.5
        request = 100

[RewardsMySQL]
    addr = "172.22.34.101:3306"
    dsn = "test:pqAgqRbLBa7afOAQ47IBlqvJcOGI9YNd@tcp(172.16.33.205:3308)/bilibili_lottery?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 5
    idle = 2
    idleTimeout ="4h"
    queryTimeout = "3s"
    execTimeout = "3s"
    tranTimeout = "3s"
    [RewardsMySQL.breaker]
        window  ="3s"
        sleep   ="100ms"
        bucket  = 10
        ratio   = 0.5
        request = 100