[httpService]
    [httpService.inner]
        addr = "0.0.0.0:8281"
        timeout = "1s"
    [httpService.outer]
        addr = "0.0.0.0:8283"
        timeout = "1s"

[xlog]
    dir = "/data/log/resource-job"

[cron]
    loadTabExt = "@every 1m"
    loadCustomConfig = "@every 1m"
    loadSkinExt = "@every 10m"
    loadBWList = "@every 1m"

[mysql]
    [mysql.show]
        addr   = "172.22.34.101:3306"
        dsn    = "show:UJYgc9UkHIaGovEDUXpTU4U0rjBpZtwb@tcp(172.22.34.101:3306)/bilibili_show?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
        active = 10
        idle   = 5
        queryTimeout = "100ms"
        execTimeout = "100ms"
        tranTimeout = "200ms"

    [mysql.resource]
        addr = "172.22.34.101:3306"
        dsn = "test_3306:UJPZaGKjpb2ylFx3HNhmLuwOYft4MCAi@tcp(172.22.34.101:3306)/bilibili_resource?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
        active = 5
        idle = 2
        idleTimeout ="1h"
        queryTimeout = "1s"
        execTimeout = "1s"
        tranTimeout = "1s"

        [db.resource.breaker]
            window = "3s"
            sleep = "100ms"
            bucket = 10
            ratio = 0.5
            request = 100

    [db.manager]
        addr   = "172.22.34.101:3306"
        dsn    = "test_3306:UJPZaGKjpb2ylFx3HNhmLuwOYft4MCAi@tcp(172.22.34.101:3306)/bilibili_manager?timeout=1s&readTimeout=1s&writeTimeout=1s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
        active = 5
        idle   = 1
        idleTimeout ="4h"
        queryTimeout = "1s"
        execTimeout = "1s"
        tranTimeout = "1s"

[redis]
    [redis.Show]
        name   = "resource-service/show"
        proto  = "tcp"
        addr   = "172.22.33.30:7942"
        active = 1024
        idle   = 12
        dialTimeout  = "80ms"
        readTimeout  = "150ms"
        writeTimeout = "150ms"
        idleTimeout  = "80s"
