[redis]
name = "archive-job/trackreport"
proto = "tcp"
addr = "127.0.0.1:20327"
active = 10
idle = 1
dialTimeout = "1s"
readTimeout = "1s"
writeTimeout = "1s"
idleTimeout = "80s"

[Log]
stdout = true

[FollowSubRedis]
key = "8e27ab7e39270b59"
secret = "477df6a068d7332a163f95abbad2079c"
group = "StatOGVFollow-MainAppSvr-JD-S"
topic = "StatOGVFollow-T"
action = "sub"

[SnStatResultSub]
key = "8e27ab7e39270b59"
secret = "477df6a068d7332a163f95abbad2079c"
group = "UgcSeasonMsg-MainAppSvr-SHJD-S"
topic = "UgcSeasonMsg-T"
action = "sub"
name = "stat-job/databus"

[Databus]
key = "8e27ab7e39270b59"
secret = "477df6a068d7332a163f95abbad2079c"
group = "ArcResult-SHJD-MainAppSvr-S"
topic = "ArcResult-SHJD-T"
action = "sub"
name = "stat-job/databus"
proto = "tcp"
idle = 1
active = 1
dialTimeout = "1s"
readTimeout = "60s"
writeTimeout = "1s"
idleTimeout = "10s"

[ViewSubRedis]
key = "8e27ab7e39270b59"
secret = "477df6a068d7332a163f95abbad2079c"
group = "StatView-MainAppSvr-SHJD-S"
topic = "StatView-T"
action = "sub"
name = "stat-job/view"
proto = "tcp"
idle = 1
active = 1
dialTimeout = "1s"
readTimeout = "60s"
writeTimeout = "1s"
idleTimeout = "10s"

[DmSubRedis]
key = "8e27ab7e39270b59"
secret = "477df6a068d7332a163f95abbad2079c"
group = "DMSubject-MainAppSvr-SHJD-S"
topic = "DMSubject-T"
action = "sub"
name = "archive-job/DMSubject"
proto = "tcp"
addr = "172.18.33.50:6205"
idle = 1
active = 1
dialTimeout = "1s"
readTimeout = "60s"
writeTimeout = "1s"
idleTimeout = "10s"

[ReplySubRedis]
key = "8e27ab7e39270b59"
secret = "477df6a068d7332a163f95abbad2079c"
group = "StatReply-MainAppSvr-SHJD-S"
topic = "StatReply-T"
action = "sub"
name = "stat-job/reply"
proto = "tcp"
idle = 1
active = 1
dialTimeout = "1s"
readTimeout = "60s"
writeTimeout = "1s"
idleTimeout = "10s"

[FavSubRedis]
key = "8e27ab7e39270b59"
secret = "477df6a068d7332a163f95abbad2079c"
group = "StatFav-MainAppSvr-SHJD-S"
topic = "StatFav-T"
action = "sub"
name = "stat-job/fav"
proto = "tcp"
idle = 1
active = 1
dialTimeout = "1s"
readTimeout = "60s"
writeTimeout = "1s"
idleTimeout = "10s"

[CoinSubRedis]
key = "8e27ab7e39270b59"
secret = "477df6a068d7332a163f95abbad2079c"
group = "StatCoin-MainAppSvr-SHJD-S"
topic = "StatCoin-T"
action = "sub"
name = "stat-job/coin"
proto = "tcp"
idle = 1
active = 1
dialTimeout = "1s"
readTimeout = "60s"
writeTimeout = "1s"
idleTimeout = "10s"

[ShareSubRedis]
key = "8e27ab7e39270b59"
secret = "477df6a068d7332a163f95abbad2079c"
group = "StatShare-MainAppSvr-SHJD-S"
topic = "StatShare-T"
action = "sub"
name = "stat-job/share"
proto = "tcp"
idle = 1
active = 1
dialTimeout = "1s"
readTimeout = "60s"
writeTimeout = "1s"
idleTimeout = "10s"

[RankSubRedis]
key = "8e27ab7e39270b59"
secret = "477df6a068d7332a163f95abbad2079c"
group = "StatRank-MainAppSvr-SHJD-S"
topic = "StatRank-T"
action = "sub"
name = "stat-job/rank"
proto = "tcp"
idle = 1
active = 1
dialTimeout = "1s"
readTimeout = "60s"
writeTimeout = "1s"
idleTimeout = "10s"

[likeSubRedis]
key = "8e27ab7e39270b59"
secret = "477df6a068d7332a163f95abbad2079c"
group = "StatLike-MainAppSvr-SHJD-S"
topic = "StatLike-T"
action = "sub"
name = "stat-job/like"
proto = "tcp"
idle = 1
active = 1
dialTimeout = "1s"
readTimeout = "60s"
writeTimeout = "1s"
idleTimeout = "10s"

[AccountNotify]
key = "8e27ab7e39270b59"
secret = "477df6a068d7332a163f95abbad2079c"
group = "AccountNotify-SHJD-MainAppSvr-S"
topic = "AccountNotify-SHJD-T"
action = "sub"
name = "archive-job/userCache"
proto = "tcp"
addr = "172.18.33.50:6205"
idle = 1
active = 1
dialTimeout = "1s"
readTimeout = "60s"
writeTimeout = "1s"
idleTimeout = "80s"
[AccountNotifySub.discovery]
    domain = "api.bilibili.co"
    key = "53e2fa226f5ad348"
    secret = "3cf6bd1b0ff671021da5f424fea4b04a"
    region = "sh"
    zone = "sh001"
    env = "prod"

[NotifyPub]
key = "8e27ab7e39270b59"
secret = "477df6a068d7332a163f95abbad2079c"
group = "ArchiveNotify-SHJD-MainAppSvr-P"
topic = "ArchiveNotify-SHJD-T"
action = "pub"
name = "notify/pub"
proto = "tcp"
idle = 10
active = 50
dialTimeout = "100ms"
readTimeout = "60s"
writeTimeout = "300ms"
idleTimeout = "10s"

[SeasonCanal]
key = "8e27ab7e39270b59"
secret = "477df6a068d7332a163f95abbad2079c"
group = "SeasonResult-Canel-MainAppSvr-SHJD-S"
topic = "SeasonResult-Canel-T"
action = "sub"

[seasonCanal]
key = "8e27ab7e39270b59"
secret = "477df6a068d7332a163f95abbad2079c"
group = "NotifySub-MainAppSvr-SHJD-S"
topic = "NotifySub-T"
action = "pub"
name = "stat-job/like"
proto = "tcp"
addr = "172.18.21.41:6205"
idle = 1
active = 1
dialTimeout = "1s"
readTimeout = "60s"
writeTimeout = "1s"
idleTimeout = "10s"

[cacheSub]
key = "8e27ab7e39270b59"
secret = "477df6a068d7332a163f95abbad2079c"
group = "NotifySub-MainAppSvr-SHJD-S"
topic = "NotifySub-T"
action = "pub"
name = "stat-job/like"
proto = "tcp"
addr = "172.18.21.41:6205"
idle = 1
active = 1
dialTimeout = "1s"
readTimeout = "60s"
writeTimeout = "1s"
idleTimeout = "10s"

[[ArchiveRPCs]]
    cluster = "group1"
    zone = "sh004"
[[ArchiveRPCs]]
    cluster = "group2"
    zone = "sh004"

[db]
[db.result]
    name = "archive_result"
    dsn = "arc_service:lizK1PZWI7GrQDhuxsc3wtvXT04kRSo6@tcp(172.22.34.101:3306)/archive_result?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8mb4"
     active = 20
    idle = 10
    idleTimeout = "4h"
    queryTimeout = "5s"
    execTimeout = "5s"
    tranTimeout = "5s"
[db.ArcRead]
    name = "bilibili_archive"
    dsn = "arc_service:lizK1PZWI7GrQDhuxsc3wtvXT04kRSo6@tcp(172.22.34.101:3306)/bilibili_archive?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8mb4"
    active = 20
    idle = 10
    idleTimeout = "4h"
    queryTimeout = "5s"
    execTimeout = "5s"
    tranTimeout = "5s"
[db.Stat]
    name = "bilibili_archive"
    dsn = "arc_service:lizK1PZWI7GrQDhuxsc3wtvXT04kRSo6@tcp(172.22.34.101:3306)/archive_stat?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8mb4"
    active = 20
    idle = 10
    idleTimeout = "4h"
    queryTimeout = "5s"
    execTimeout = "5s"
    tranTimeout = "5s"


[[archiveGRPC]]
    cluster = ""
[[archiveGRPC]]
    cluster = ""

[CacheSub]
key = "8e27ab7e39270b59"
secret = "477df6a068d7332a163f95abbad2079c"
group = "ArchiveUserCache-MainAppSvr-S"
topic = "ArchiveUserCache-T"
action = "sub"
name = "archive-job/userCache"
proto = "tcp"
addr = "172.18.33.50:6205"
idle = 1
active = 1
dialTimeout = "1s"
readTimeout = "60s"
writeTimeout = "1s"
idleTimeout = "80s"

[StatRedis]
name   = "stat-serivce"
proto  = "tcp"
addr   = "127.0.0.1:20327"
active = 5
idle   = 1
dialTimeout  = "30ms"
readTimeout  = "800ms"
writeTimeout = "800ms"
idleTimeout  = "80s"

[[ArcRedises]]
    name   = "archive-service"
    proto  = "tcp"
    addr   = "127.0.0.1:20327"
    active = 1024
    idle   = 64
    dialTimeout  = "30ms"
    readTimeout  = "800ms"
    writeTimeout = "800ms"
    idleTimeout  = "80s"

[custom]
RedisAvExpireTime=259200
procCount=70
CacheGray = 50
CanalAlertTime = 10