[Redis]
name = "archive-job/track"
proto = "unix"
addr = "/tmp/shjd-archive-service-group1-redis.sock"
active = 1000
idle = 20
dialTimeout = "80ms"
readTimeout = "200ms"
writeTimeout = "200ms"
idleTimeout = "80s"

[Databus]
key = "8e27ab7e39270b59"
secret = "477df6a068d7332a163f95abbad2079c"
group = "ArcResult-SHJD-MainAppSvr-S"
topic = "ArcResult-SHJD-T"
action = "sub"
name = "stat-job/databus"
proto = "tcp"
addr = "172.18.21.41:6205"
idle = 1
active = 1
dialTimeout = "1s"
readTimeout = "60s"
writeTimeout = "1s"
idleTimeout = "10s"

[ViewSubRedis]
key = "8e27ab7e39270b59"
secret = "477df6a068d7332a163f95abbad2079c"
group = "StatView-MainAppSvr-SHJD-S"
topic = "StatView-T"
action = "sub"
name = "stat-job/view"
proto = "tcp"
addr = "172.18.21.41:6205"
idle = 1
active = 1
dialTimeout = "1s"
readTimeout = "60s"
writeTimeout = "1s"
idleTimeout = "10s"

[DmSubRedis]
key = "8e27ab7e39270b59"
secret = "477df6a068d7332a163f95abbad2079c"
group = "StatDM-MainAppSvr-SHJD-S"
topic = "StatDM-T"
action = "sub"
name = "stat-job/dm"
proto = "tcp"
addr = "172.18.21.41:6205"
idle = 1
active = 1
dialTimeout = "1s"
readTimeout = "60s"
writeTimeout = "1s"
idleTimeout = "10s"

[ReplySubRedis]
key = "8e27ab7e39270b59"
secret = "477df6a068d7332a163f95abbad2079c"
group = "StatReply-MainAppSvr-SHJD-S"
topic = "StatReply-T"
action = "sub"
name = "stat-job/reply"
proto = "tcp"
addr = "172.18.21.41:6205"
idle = 1
active = 1
dialTimeout = "1s"
readTimeout = "60s"
writeTimeout = "1s"
idleTimeout = "10s"

[FavSubRedis]
key = "8e27ab7e39270b59"
secret = "477df6a068d7332a163f95abbad2079c"
group = "StatFav-MainAppSvr-SHJD-S"
topic = "StatFav-T"
action = "sub"
name = "stat-job/fav"
proto = "tcp"
addr = "172.18.21.41:6205"
idle = 1
active = 1
dialTimeout = "1s"
readTimeout = "60s"
writeTimeout = "1s"
idleTimeout = "10s"

[CoinSubRedis]
key = "8e27ab7e39270b59"
secret = "477df6a068d7332a163f95abbad2079c"
group = "StatCoin-MainAppSvr-SHJD-S"
topic = "StatCoin-T"
action = "sub"
name = "stat-job/coin"
proto = "tcp"
addr = "172.18.21.41:6205"
idle = 1
active = 1
dialTimeout = "1s"
readTimeout = "60s"
writeTimeout = "1s"
idleTimeout = "10s"

[ShareSubRedis]
key = "8e27ab7e39270b59"
secret = "477df6a068d7332a163f95abbad2079c"
group = "StatShare-MainAppSvr-SHJD-S"
topic = "StatShare-T"
action = "sub"
name = "stat-job/share"
proto = "tcp"
addr = "172.18.21.41:6205"
idle = 1
active = 1
dialTimeout = "1s"
readTimeout = "60s"
writeTimeout = "1s"
idleTimeout = "10s"

[RankSubRedis]
key = "8e27ab7e39270b59"
secret = "477df6a068d7332a163f95abbad2079c"
group = "StatRank-MainAppSvr-SHJD-S"
topic = "StatRank-T"
action = "sub"
name = "stat-job/rank"
proto = "tcp"
addr = "172.18.21.41:6205"
idle = 1
active = 1
dialTimeout = "1s"
readTimeout = "60s"
writeTimeout = "1s"
idleTimeout = "10s"
	
[likeSubRedis]
key = "8e27ab7e39270b59"
secret = "477df6a068d7332a163f95abbad2079c"
group = "StatLike-MainAppSvr-SHJD-S"
topic = "StatLike-T"
action = "sub"
name = "stat-job/like"
proto = "tcp"
addr = "172.18.21.41:6205"
idle = 1
active = 1
dialTimeout = "1s"
readTimeout = "60s"
writeTimeout = "1s"
idleTimeout = "10s"

[NotifyPub]
key = "8e27ab7e39270b59"
secret = "477df6a068d7332a163f95abbad2079c"
group = "NotifySub-MainAppSvr-SHJD-S"
topic = "NotifySub-T"
action = "pub"
name = "stat-job/like"
proto = "tcp"
addr = "172.18.21.41:6205"
idle = 1
active = 1
dialTimeout = "1s"
readTimeout = "60s"
writeTimeout = "1s"
idleTimeout = "10s"

[AccountNotify]
key = "8e27ab7e39270b59"
secret = "477df6a068d7332a163f95abbad2079c"
group = "NotifySub-MainAppSvr-SHJD-S"
topic = "NotifySub-T"
action = "pub"
name = "stat-job/like"
proto = "tcp"
addr = "172.18.21.41:6205"
idle = 1
active = 1
dialTimeout = "1s"
readTimeout = "60s"
writeTimeout = "1s"
idleTimeout = "10s"

[seasonCanal]
key = "8e27ab7e39270b59"
secret = "477df6a068d7332a163f95abbad2079c"
group = "NotifySub-MainAppSvr-SHJD-S"
topic = "NotifySub-T"
action = "pub"
name = "stat-job/like"
proto = "tcp"
addr = "172.18.21.41:6205"
idle = 1
active = 1
dialTimeout = "1s"
readTimeout = "60s"
writeTimeout = "1s"
idleTimeout = "10s"

[cacheSub]
key = "8e27ab7e39270b59"
secret = "477df6a068d7332a163f95abbad2079c"
group = "NotifySub-MainAppSvr-SHJD-S"
topic = "NotifySub-T"
action = "pub"
name = "stat-job/like"
proto = "tcp"
addr = "172.18.21.41:6205"
idle = 1
active = 1
dialTimeout = "1s"
readTimeout = "60s"
writeTimeout = "1s"
idleTimeout = "10s"

[[ArchiveRPCs]]
    cluster = "group1"
    zone = "sh004"
[[ArchiveRPCs]]
    cluster = "group2"
    zone = "sh004"

[[memcaches]]
    name = "archive-service"
    proto = "tcp"
    addr = "127.0.0.1:11211"
    active = 50
    idle = 10
    dialTimeout = "30ms"
    readTimeout = "200ms"
    writeTimeout = "200ms"
    idleTimeout = "80s"
    archiveExpire = "10h"
    videoExpire = "10h"
[[memcaches]]
    name = "archive-service"
    proto = "tcp"
    addr = "127.0.0.1:11211"
    active = 50
    idle = 10
    dialTimeout = "30ms"
    readTimeout = "200ms"
    writeTimeout = "200ms"
    idleTimeout = "80s"
    archiveExpire = "10h"
    videoExpire = "10h"

[db]
[db.result]
    name = "archive_result"
    dsn = "test:test@tcp(172.22.33.205:3306)/archive_result?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8"
    active = 20
    idle = 10
    idleTimeout = "4h"
    queryTimeout = "5s"
    execTimeout = "5s"
    tranTimeout = "5s"

[StatRedis]
name   = "stat-serivce"
proto  = "tcp"
addr   = "127.0.0.1:6379"
active = 1024
idle   = 64
dialTimeout  = "30ms"
readTimeout  = "800ms"
writeTimeout = "800ms"
idleTimeout  = "80s"

[[ArcRedises]]
    name   = "archive-service"
    proto  = "tcp"
    addr   = "127.0.0.1:6380"
    active = 1024
    idle   = 64
    dialTimeout  = "30ms"
    readTimeout  = "800ms"
    writeTimeout = "800ms"
    idleTimeout  = "80s"

[[ArcRedises]]
    name   = "archive-service"
    proto  = "tcp"
    addr   = "127.0.0.1:6380"
    active = 1024
    idle   = 64
    dialTimeout  = "30ms"
    readTimeout  = "800ms"
    writeTimeout = "800ms"
    idleTimeout  = "80s"

[custom]
RedisAvExpireTime=259200
procCount=70
