
POST {{baseUrl}}/app/mod/module/update
Content-Type: application/x-www-form-urlencoded
Cookie: {{Cookie}}

module_id=1307445&remark=testess&is_wifi=true&zip_check=true&compress=original

###

POST {{baseUrl}}/app/mod/module/update
Content-Type: application/x-www-form-urlencoded
Cookie: {{Cookie}}

module_id=1307446&remark=testess&is_wifi=true&zip_check=true

###