// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: go-gateway/app/app-svr/misaka/interface/internal/model/web/web.proto

/*
Package web is a generated protocol buffer package.

It is generated from these files:

	go-gateway/app/app-svr/misaka/interface/internal/model/web/web.proto

It has these top-level messages:

	Info
	Data
*/
package web

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Info struct {
	Data      *Data  `protobuf:"bytes,1,opt,name=Data" json:"data"`
	IP        string `protobuf:"bytes,2,opt,name=IP,proto3" json:"ip"`
	Country   string `protobuf:"bytes,3,opt,name=country,proto3" json:"country"`
	Province  string `protobuf:"bytes,4,opt,name=province,proto3" json:"province"`
	City      string `protobuf:"bytes,5,opt,name=city,proto3" json:"city"`
	ISP       string `protobuf:"bytes,6,opt,name=ISP,proto3" json:"isp"`
	Timestamp int64  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"@timestamp"`
}

func (m *Info) Reset()                    { *m = Info{} }
func (m *Info) String() string            { return proto.CompactTextString(m) }
func (*Info) ProtoMessage()               {}
func (*Info) Descriptor() ([]byte, []int) { return fileDescriptorWeb, []int{0} }

func (m *Info) GetData() *Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Info) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

func (m *Info) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Info) GetProvince() string {
	if m != nil {
		return m.Province
	}
	return ""
}

func (m *Info) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Info) GetISP() string {
	if m != nil {
		return m.ISP
	}
	return ""
}

func (m *Info) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type Data struct {
	LogID          int64             `protobuf:"varint,1,opt,name=logID,proto3" json:"log_id"`
	Browser        string            `protobuf:"bytes,2,opt,name=browser,proto3" json:"browser"`
	Uri            string            `protobuf:"bytes,3,opt,name=uri,proto3" json:"uri"`
	UserAgent      string            `protobuf:"bytes,4,opt,name=userAgent,proto3" json:"user_agent"`
	Buvid          string            `protobuf:"bytes,5,opt,name=buvid,proto3" json:"buvid"`
	Referrer       string            `protobuf:"bytes,6,opt,name=referrer,proto3" json:"referrer"`
	Mid            int64             `protobuf:"varint,7,opt,name=mid,proto3" json:"mid"`
	ExtendedFields map[string]string `protobuf:"bytes,8,rep,name=extended_fields,json=extendedFields" json:"extended_fields" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *Data) Reset()                    { *m = Data{} }
func (m *Data) String() string            { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()               {}
func (*Data) Descriptor() ([]byte, []int) { return fileDescriptorWeb, []int{1} }

func (m *Data) GetLogID() int64 {
	if m != nil {
		return m.LogID
	}
	return 0
}

func (m *Data) GetBrowser() string {
	if m != nil {
		return m.Browser
	}
	return ""
}

func (m *Data) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *Data) GetUserAgent() string {
	if m != nil {
		return m.UserAgent
	}
	return ""
}

func (m *Data) GetBuvid() string {
	if m != nil {
		return m.Buvid
	}
	return ""
}

func (m *Data) GetReferrer() string {
	if m != nil {
		return m.Referrer
	}
	return ""
}

func (m *Data) GetMid() int64 {
	if m != nil {
		return m.Mid
	}
	return 0
}

func (m *Data) GetExtendedFields() map[string]string {
	if m != nil {
		return m.ExtendedFields
	}
	return nil
}

func init() {
	proto.RegisterType((*Info)(nil), "app.misaka.v1.Info")
	proto.RegisterType((*Data)(nil), "app.misaka.v1.Data")
}
func (m *Info) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Info) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Data != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintWeb(dAtA, i, uint64(m.Data.Size()))
		n1, err := m.Data.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if len(m.IP) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintWeb(dAtA, i, uint64(len(m.IP)))
		i += copy(dAtA[i:], m.IP)
	}
	if len(m.Country) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintWeb(dAtA, i, uint64(len(m.Country)))
		i += copy(dAtA[i:], m.Country)
	}
	if len(m.Province) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintWeb(dAtA, i, uint64(len(m.Province)))
		i += copy(dAtA[i:], m.Province)
	}
	if len(m.City) > 0 {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintWeb(dAtA, i, uint64(len(m.City)))
		i += copy(dAtA[i:], m.City)
	}
	if len(m.ISP) > 0 {
		dAtA[i] = 0x32
		i++
		i = encodeVarintWeb(dAtA, i, uint64(len(m.ISP)))
		i += copy(dAtA[i:], m.ISP)
	}
	if m.Timestamp != 0 {
		dAtA[i] = 0x38
		i++
		i = encodeVarintWeb(dAtA, i, uint64(m.Timestamp))
	}
	return i, nil
}

func (m *Data) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Data) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.LogID != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintWeb(dAtA, i, uint64(m.LogID))
	}
	if len(m.Browser) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintWeb(dAtA, i, uint64(len(m.Browser)))
		i += copy(dAtA[i:], m.Browser)
	}
	if len(m.Uri) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintWeb(dAtA, i, uint64(len(m.Uri)))
		i += copy(dAtA[i:], m.Uri)
	}
	if len(m.UserAgent) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintWeb(dAtA, i, uint64(len(m.UserAgent)))
		i += copy(dAtA[i:], m.UserAgent)
	}
	if len(m.Buvid) > 0 {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintWeb(dAtA, i, uint64(len(m.Buvid)))
		i += copy(dAtA[i:], m.Buvid)
	}
	if len(m.Referrer) > 0 {
		dAtA[i] = 0x32
		i++
		i = encodeVarintWeb(dAtA, i, uint64(len(m.Referrer)))
		i += copy(dAtA[i:], m.Referrer)
	}
	if m.Mid != 0 {
		dAtA[i] = 0x38
		i++
		i = encodeVarintWeb(dAtA, i, uint64(m.Mid))
	}
	if len(m.ExtendedFields) > 0 {
		for k := range m.ExtendedFields {
			dAtA[i] = 0x42
			i++
			v := m.ExtendedFields[k]
			mapSize := 1 + len(k) + sovWeb(uint64(len(k))) + 1 + len(v) + sovWeb(uint64(len(v)))
			i = encodeVarintWeb(dAtA, i, uint64(mapSize))
			dAtA[i] = 0xa
			i++
			i = encodeVarintWeb(dAtA, i, uint64(len(k)))
			i += copy(dAtA[i:], k)
			dAtA[i] = 0x12
			i++
			i = encodeVarintWeb(dAtA, i, uint64(len(v)))
			i += copy(dAtA[i:], v)
		}
	}
	return i, nil
}

func encodeVarintWeb(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *Info) Size() (n int) {
	var l int
	_ = l
	if m.Data != nil {
		l = m.Data.Size()
		n += 1 + l + sovWeb(uint64(l))
	}
	l = len(m.IP)
	if l > 0 {
		n += 1 + l + sovWeb(uint64(l))
	}
	l = len(m.Country)
	if l > 0 {
		n += 1 + l + sovWeb(uint64(l))
	}
	l = len(m.Province)
	if l > 0 {
		n += 1 + l + sovWeb(uint64(l))
	}
	l = len(m.City)
	if l > 0 {
		n += 1 + l + sovWeb(uint64(l))
	}
	l = len(m.ISP)
	if l > 0 {
		n += 1 + l + sovWeb(uint64(l))
	}
	if m.Timestamp != 0 {
		n += 1 + sovWeb(uint64(m.Timestamp))
	}
	return n
}

func (m *Data) Size() (n int) {
	var l int
	_ = l
	if m.LogID != 0 {
		n += 1 + sovWeb(uint64(m.LogID))
	}
	l = len(m.Browser)
	if l > 0 {
		n += 1 + l + sovWeb(uint64(l))
	}
	l = len(m.Uri)
	if l > 0 {
		n += 1 + l + sovWeb(uint64(l))
	}
	l = len(m.UserAgent)
	if l > 0 {
		n += 1 + l + sovWeb(uint64(l))
	}
	l = len(m.Buvid)
	if l > 0 {
		n += 1 + l + sovWeb(uint64(l))
	}
	l = len(m.Referrer)
	if l > 0 {
		n += 1 + l + sovWeb(uint64(l))
	}
	if m.Mid != 0 {
		n += 1 + sovWeb(uint64(m.Mid))
	}
	if len(m.ExtendedFields) > 0 {
		for k, v := range m.ExtendedFields {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovWeb(uint64(len(k))) + 1 + len(v) + sovWeb(uint64(len(v)))
			n += mapEntrySize + 1 + sovWeb(uint64(mapEntrySize))
		}
	}
	return n
}

func sovWeb(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozWeb(x uint64) (n int) {
	return sovWeb(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Info) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWeb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Info: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Info: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWeb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWeb
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Data == nil {
				m.Data = &Data{}
			}
			if err := m.Data.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IP", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWeb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWeb
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IP = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Country", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWeb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWeb
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Country = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Province", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWeb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWeb
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Province = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field City", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWeb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWeb
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.City = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ISP", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWeb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWeb
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ISP = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			m.Timestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWeb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Timestamp |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipWeb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthWeb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Data) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWeb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Data: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Data: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LogID", wireType)
			}
			m.LogID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWeb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LogID |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Browser", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWeb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWeb
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Browser = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Uri", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWeb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWeb
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Uri = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserAgent", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWeb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWeb
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserAgent = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Buvid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWeb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWeb
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Buvid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Referrer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWeb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWeb
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Referrer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mid", wireType)
			}
			m.Mid = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWeb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Mid |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExtendedFields", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWeb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWeb
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ExtendedFields == nil {
				m.ExtendedFields = make(map[string]string)
			}
			var mapkey string
			var mapvalue string
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowWeb
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowWeb
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= (uint64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthWeb
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var stringLenmapvalue uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowWeb
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapvalue |= (uint64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapvalue := int(stringLenmapvalue)
					if intStringLenmapvalue < 0 {
						return ErrInvalidLengthWeb
					}
					postStringIndexmapvalue := iNdEx + intStringLenmapvalue
					if postStringIndexmapvalue > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = string(dAtA[iNdEx:postStringIndexmapvalue])
					iNdEx = postStringIndexmapvalue
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipWeb(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthWeb
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.ExtendedFields[mapkey] = mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipWeb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthWeb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipWeb(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowWeb
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowWeb
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowWeb
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthWeb
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowWeb
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipWeb(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthWeb = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowWeb   = fmt.Errorf("proto: integer overflow")
)

func init() {
	proto.RegisterFile("go-gateway/app/app-svr/misaka/interface/internal/model/web/web.proto", fileDescriptorWeb)
}

var fileDescriptorWeb = []byte{
	// 525 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0x41, 0x8e, 0xd3, 0x30,
	0x14, 0x55, 0x92, 0xb6, 0xd3, 0xba, 0x30, 0x80, 0x8b, 0x50, 0x18, 0xa1, 0xa6, 0x1a, 0x09, 0xd1,
	0x05, 0x4d, 0x34, 0xc3, 0x06, 0xb1, 0x62, 0xa2, 0x0e, 0x52, 0x77, 0x95, 0xd9, 0xb1, 0xa9, 0x9c,
	0xc4, 0x09, 0xd6, 0x24, 0x71, 0xe4, 0x38, 0x2d, 0x3d, 0x02, 0x37, 0xe1, 0x28, 0x2c, 0x39, 0x41,
	0x84, 0xba, 0xcc, 0x29, 0x90, 0x7f, 0xd2, 0x8e, 0x06, 0xcd, 0xa2, 0xbf, 0xef, 0xbf, 0xff, 0x6c,
	0xbd, 0xff, 0x62, 0xb4, 0x4c, 0xc4, 0x22, 0x14, 0x59, 0x26, 0x72, 0x8f, 0x16, 0x85, 0xc7, 0x73,
	0xc5, 0x64, 0x4c, 0x43, 0xe6, 0x65, 0x94, 0x03, 0xb5, 0xc8, 0x78, 0x49, 0xef, 0x68, 0x3b, 0xc9,
	0x69, 0xea, 0x65, 0x22, 0x62, 0xa9, 0xb7, 0x63, 0x81, 0xfe, 0xb9, 0x85, 0x14, 0x4a, 0xe0, 0xa7,
	0xb4, 0x28, 0xdc, 0x56, 0xe8, 0x6e, 0xaf, 0x2e, 0x16, 0x09, 0x57, 0xdf, 0xab, 0xc0, 0x0d, 0x45,
	0xe6, 0x25, 0x22, 0x11, 0x1e, 0xa8, 0x82, 0x2a, 0x86, 0x0e, 0x1a, 0x40, 0xed, 0xe9, 0xcb, 0x9f,
	0x26, 0xea, 0xad, 0xf2, 0x58, 0xe0, 0x2b, 0xd4, 0x5b, 0x52, 0x45, 0x6d, 0x63, 0x66, 0xcc, 0xc7,
	0xd7, 0x13, 0xf7, 0xc1, 0xad, 0xae, 0x1e, 0xf9, 0xc3, 0xa6, 0x76, 0x7a, 0x11, 0x55, 0x94, 0x80,
	0x14, 0xbf, 0x42, 0xe6, 0x6a, 0x6d, 0x9b, 0x33, 0x63, 0x3e, 0xf2, 0x07, 0x4d, 0xed, 0x98, 0xbc,
	0x20, 0xe6, 0x6a, 0x8d, 0xdf, 0xa2, 0xb3, 0x50, 0x54, 0xb9, 0x92, 0x7b, 0xdb, 0x82, 0xe1, 0xb8,
	0xa9, 0x9d, 0x23, 0x45, 0x8e, 0x00, 0xcf, 0xd1, 0xb0, 0x90, 0x62, 0xcb, 0xf3, 0x90, 0xd9, 0x3d,
	0xd0, 0x3d, 0x69, 0x6a, 0xe7, 0xc4, 0x91, 0x13, 0xc2, 0x6f, 0x50, 0x2f, 0xe4, 0x6a, 0x6f, 0xf7,
	0x41, 0x05, 0x36, 0x74, 0x4f, 0xa0, 0xe2, 0xd7, 0xc8, 0x5a, 0x7d, 0x5d, 0xdb, 0x03, 0x18, 0x9e,
	0x35, 0xb5, 0x63, 0xf1, 0xb2, 0x20, 0x9a, 0xc3, 0xef, 0xd1, 0x48, 0xf1, 0x8c, 0x95, 0x8a, 0x66,
	0x85, 0x7d, 0x36, 0x33, 0xe6, 0x96, 0x7f, 0xde, 0xd4, 0x0e, 0xfa, 0x7c, 0x62, 0xc9, 0xbd, 0xe0,
	0xf2, 0x97, 0xd5, 0x66, 0x80, 0x67, 0xa8, 0x9f, 0x8a, 0x64, 0xb5, 0x84, 0x30, 0x2c, 0x1f, 0x35,
	0xb5, 0x33, 0x48, 0x45, 0xb2, 0xe1, 0x11, 0x69, 0x07, 0x7a, 0xc5, 0x40, 0x8a, 0x5d, 0xc9, 0x64,
	0xb7, 0x3f, 0xac, 0xd8, 0x51, 0xe4, 0x08, 0xb4, 0xb5, 0x4a, 0xf2, 0x2e, 0x05, 0xb0, 0x56, 0x49,
	0x4e, 0x74, 0xd1, 0xd6, 0xaa, 0x92, 0xc9, 0x9b, 0x84, 0xe5, 0xaa, 0x5b, 0x1f, 0xac, 0x69, 0x72,
	0x43, 0x35, 0x4b, 0xee, 0x05, 0xd8, 0x41, 0xfd, 0xa0, 0xda, 0xf2, 0xa8, 0x8b, 0x60, 0xd4, 0xd4,
	0x4e, 0x4b, 0x90, 0xf6, 0x4f, 0x87, 0x29, 0x59, 0xcc, 0xa4, 0x64, 0xb2, 0x4b, 0x02, 0xc2, 0x3c,
	0x72, 0xe4, 0x84, 0xb4, 0xa7, 0x8c, 0x47, 0x5d, 0x1a, 0xe0, 0x29, 0xe3, 0x11, 0xd1, 0x05, 0x33,
	0xf4, 0x8c, 0xfd, 0x50, 0x2c, 0x8f, 0x58, 0xb4, 0x89, 0x39, 0x4b, 0xa3, 0xd2, 0x1e, 0xce, 0xac,
	0xf9, 0xf8, 0xfa, 0xdd, 0x23, 0xcf, 0xc1, 0xbd, 0xed, 0xa4, 0x5f, 0x40, 0x79, 0xab, 0xbf, 0xa9,
	0x3f, 0x69, 0x6a, 0xe7, 0xff, 0x3b, 0xc8, 0x39, 0x7b, 0xa0, 0xbc, 0xb8, 0x41, 0x93, 0x47, 0xce,
	0xe2, 0xe7, 0xc8, 0xba, 0x63, 0x7b, 0xc8, 0x7c, 0x44, 0x34, 0xc4, 0x2f, 0x51, 0x7f, 0x4b, 0xd3,
	0x8a, 0xb5, 0x19, 0x93, 0xb6, 0xf9, 0x64, 0x7e, 0x34, 0xfc, 0x17, 0xbf, 0x0f, 0x53, 0xe3, 0xcf,
	0x61, 0x6a, 0xfc, 0x3d, 0x4c, 0x8d, 0x6f, 0xd6, 0x8e, 0x05, 0xc1, 0x00, 0x1e, 0xf4, 0x87, 0x7f,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x07, 0xf6, 0xb5, 0x73, 0x56, 0x03, 0x00, 0x00,
}
