[Log]
  ###dir = "/data/log/activity-admin/"
  stdout = true
[HTTPServer]
  addr = "0.0.0.0:7741"
  maxListen = 1000
  timeout = "10m"
  readTimeout = "10m"
  writeTimeout = "10m"

[httpClient]
  key = "b1014d7c339a5649"
  secret = "75b74b612aa792b112e6504cae44c319"
  dial = "10s"
  timeout = "10s"
  keepAlive = "60s"
[httpClient.breaker]
  window  ="3s"
  sleep   ="100ms"
  bucket  = 10
  ratio   = 0.5
  request = 100

[httpGameClient]
key    = "EeOpM531WqQnBvu4"
secret = "gHtKtXTHZJDqGP1tg9ORFs0YWV3kW12V"
dial      = "100ms"
timeout   = "500ms"
keepAlive = "60s"

[orm]
  dsn = "lottery:D8B9aJcnMHh2SWzVvCQiIJ2qYzfMvfUg@tcp(172.22.34.101:3306)/bilibili_lottery?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
  active = 5
  idle = 5
  idleTimeout = "4h"

[redis]
  name = "activity-admin"
  proto = "tcp"
  addr = "127.0.0.1:20089"
  idle = 64
  active = 1024
  dialTimeout = "1s"
  readTimeout = "1s"
  writeTimeout = "1s"
  idleTimeout = "80s"
  expire = "10s"

[Host]
  dynamic = "http://uat-api.vc.bilibili.co"
  gameCo = "http://uat-game-center-open-api.bilibili.co"
  manGaCo = "http://uat-manga.bilibili.co"

[Up]
  SenderUid = 88895139
  PassContent = "您发起的ar活动已通过审核"
  UnPassContent = "很抱歉，您发起的ar活动未能通过审核，请重新发起活动"
  actSenderUid = 88895139

[infocConf]
[infocConf.CloudInfoc]
  cloudLogID =004758
