#infoc
[Node]
taskID = "002298"
proto   = "tcp"
addr    = "dataflow.bilibili.co:5402"
chanSize = 10240

[Mark]
taskID = "002652"
proto   = "tcp"
addr    = "dataflow.bilibili.co:5402"
chanSize = 10240

[Custom]
qteStyle = 2
edgeGraphWhiteMidPct = 1
edgeGraphWhitelist = [123,321,1234,4321,12345]
edgeGraphPreviewSwitch = 0
hvarCacheHasCursor = 0

[SteinsGate]
    key = "8e27ab7e39270b59"
    secret = "477df6a068d7332a163f95abbad2079c"
    group = "SteinsGate-MainAppSvr-P"
    topic = "SteinsGate-T"
    action = "pub"
    proto = "tcp"
    addr = "172.18.33.50:6205"
    idle = 100
    active = 100
    dialTimeout = "1s"
    readTimeout = "60s"
    writeTimeout = "1s"
    idleTimeout = "10s"

[ArcInteractivePub]
    key = "9765cdac5894f2ba"
    secret = "f4237d712c3ed1e7fab0137b81418b14"
    group = "Archive-Interactive-MainWebSvr-P"
    topic = "Archive-Interactive-T"
    action = "pub"
    proto = "tcp"
    addr = "172.18.33.50:6205"
    idle = 100
    active = 100
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"

[Redis]
    RecordExpiration = "24h"
    HvarExpirationMinH = "1h"
    HvarExpirationMaxH = "18h"
    [Redis.Graph]
    name   = "app-job/graph"
    proto  = "tcp"
    addr   = "0.0.0.0:6379"
    active = 1024
    idle   = 64
    dialTimeout  = "30ms"
    readTimeout  = "1800ms"
    writeTimeout = "1800ms"
    idleTimeout  = "80s"

[wechat]
    wxkey = "9c178e51a7d4dc8aa1dbef0c790b06e7574c4d0etracehubtuhui@bilibili.com"
    wxTitle = "互动视频新剧情树消息"
    wxUser = "qiujianwen,hongmei,xueye,xuqiujie,liuqianghua,zhuyanhua,dongyuchun,huangsenmiao,zhangwenhong,zhaoxiping,chenyidong,liuheyi,wuwenlong,yangfan01,liudongfang,zhanghailong,wuheng,zhengfei,menglinghe,zhaogang,balingyan,jinyejun,dogchenglong,duziwei,chenyuanrui,wangxu04,luomengyan,liweijia"

[bvc]
    key = "d5487ea02b97"

[rule]
    allowCommitTime = "2017-10-17T00:00:00+08:00"
    GraphMids = [908085,48155,1684013,98656092,35053212,3479095]
    retrySpan = "50ms"
    [rule.PrivateMsg]
       MC = "1_24_1"
       passTitle = "您的剧情树已通过审核"
       passContent = "您的互动视频《%s》应用的剧情树已经通过审核。"
       rejectTitle = "您的剧情树已被退回"
       rejectContent = "您的互动视频《%s》应用的剧情树未能通过审核。原因：%s。"
    [rule.ToastMsg]
       needLogin = "登陆后才能体验全部结局哦～"
       graphUpdate = "剧情被修改无法继续"

#http
[server]
    addr = "0.0.0.0:8000"
    timeout = "1s"
[videoClient]
    key    = "7c7ac0db1aa05587"
    secret = "9a6d62d93290c5f771ad381e9ca23f26"
    dial = "80ms"
    timeout = "500ms"
    keepAlive = "60s"
    timer = 1000
[wechatClient]
    key = "7c7ac0db1aa05587"
    secret = "9a6d62d93290c5f771ad381e9ca23f26"
    dial = "100ms"
    timeout = "800ms"
    keepAlive = "60s"
    timer = 1000
[host]
    videoUp = "http://archive.api.bilibili.co"
    merak = "http://merak.bilibili.co"
    bvc = "http://172.16.38.189:7086"
    #bvc = "http://bvc-storage.bilibili.co"
    bfs = "http://uat-bfs.bilibili.co"

[memcache]
	[memcache.graph]
        name   = "app-job/graph"
        proto  = "tcp"
        addr   = "localhost:11211"
        active = 1024
        idle   = 64
        dialTimeout  = "30ms"
        readTimeout  = "800ms"
        writeTimeout = "800ms"
        idleTimeout  = "80s"
    [memcache.Expirations]
        RecordExpire = "3h"
        GraphExpire = "168h"
        HvarExpire = "168h"
        MarkExpire = "168h"

[mysql]
    [mysql.steinsgate]
    addr = "172.16.33.205:3308"
    dsn = "test_3306:UJPZaGKjpb2ylFx3HNhmLuwOYft4MCAi@tcp(172.22.34.101:3306)/steins_gate?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
#    dsn = "test:test@tcp(172.16.33.205:3308)/steins_gate?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 5
    idle = 2
    idleTimeout ="4h"
    queryTimeout = "1s"
    execTimeout = "1s"
    tranTimeout = "2s"
    [mysql.steinsgate.breaker]
        window = "3s"
        sleep = "100ms"
        bucket = 10
        ratio = 0.5
        request = 100

[Xlog]
    # dir = "/data/log/steins-gate-service/"
    stdout = true

[Interval]
    SkinInterval = "1m"

[DefaultSkin]
    ChoiceImage = "http://uat-i0.hdslb.com/bfs/activity-plat/static/9bdd988aed64a23976d6d5494533a450/63f40dfd5802d6ff7a4b47252ac78e4c2c616844.png"
    TitleTextColor = "ffffffff"
    TitleShadowColor = "33000000"
    TitleShadowOffsetX = 0.00
    TitleShadowOffsetY = 1.00
    TitleShadowRadius = 1.00
    ProgressbarColor = "ffffffff"
    ProgressbarShadowColor = "000000cc"