package protocard

import (
	appcardproto "go-gateway/app/app-svr/app-card/interface/model/card/proto"
)

// All Base definitation
type (
	Base          = appcardproto.Base
	Button        = appcardproto.Button
	ThreePoint    = appcardproto.ThreePoint
	DislikeReason = appcardproto.DislikeReason
	Args          = appcardproto.Args
	PlayerArgs    = appcardproto.PlayerArgs
	Mask          = appcardproto.Mask
	Avatar        = appcardproto.Avatar
	ThreePointV2  = appcardproto.ThreePointV2
	ThreePointV3  = appcardproto.ThreePointV3
	ThreePointV4  = appcardproto.ThreePointV4
	SharePlane    = appcardproto.SharePlane
	WatchLater    = appcardproto.WatchLater
	ReasonStyle   = appcardproto.ReasonStyle
	LikeButton    = appcardproto.LikeButton
	Up            = appcardproto.Up
	ChannelBadge  = appcardproto.ChannelBadge
	Relation      = appcardproto.Relation
)

// All Cards definination
type (
	SmallCoverV2         = appcardproto.SmallCoverV2
	MiddleCoverV2        = appcardproto.MiddleCoverV2
	LargeCoverV2         = appcardproto.LargeCoverV2
	ThreeItemV2          = appcardproto.ThreeItemV2
	ThreeItemV2Item      = appcardproto.ThreeItemV2Item
	SmallCoverV4         = appcardproto.SmallCoverV4
	TwoItemV2            = appcardproto.TwoItemV2
	TwoItemV2Item        = appcardproto.TwoItemV2Item
	LargeCoverV3         = appcardproto.LargeCoverV3
	ThreePicV3           = appcardproto.ThreePicV3
	OnePicV3             = appcardproto.OnePicV3
	SmallCoverV7         = appcardproto.SmallCoverV7
	SmallCoverV9         = appcardproto.SmallCoverV9
	SmallCoverConvergeV2 = appcardproto.SmallCoverConvergeV2
	SmallChannelSpecial  = appcardproto.SmallChannelSpecial
	LargeCoverV5         = appcardproto.LargeCoverV5
)
