[Server]
    addr = "0.0.0.0:8000"
    timeout = "1s"

[Client]
    key    = "e7482d29be4a95b8"
    secret = "9e803791cdef756e75faee68e12b7442"
    dial      = "100ms"
    timeout   = "250ms"
    keepAlive = "60s"
    timer = 10
