# This is a TOML document. Boom.
env     = "uat"
tick    = "1m"
fawkesTick = "1m"


[custom]
tick = "1m"
TransferSwitch = true
TransferGroup = 18
NewDoubleMids = [1671898,5449491,9599990,10253788,420749785,12754559,268339763,17178738,299109508,899512,6967397,77232149,3479095,27637930,57870006,96945971,266665413,20980174,3250475,4126121,8218715,431797187,14137123,14139334,206790694,388745658,1684013,108669,50838324,105232234,14135892,38988902]
autoPlayMids = [1111112136,1111115403,1111114965,27515232]
#2019-09-05 15:00:00
bannerAbtestTime = 1567666800
dalaomids = [1684013,98656092]
gifSwitch = 0
newAdAbtest = 100
expireNewUser = "1m"
FeedLiveSwitch = true
mogulMids = [108669,7269078,12503042,143803174,314079753,98656092,768525,10778932,377163897,27833317]
autoRefreshTime = "1m"
newAdBigCardAbtest = 100
WXBStartTime = 1585928043
WXBEndTime = 1586014443
StoryThreePoint=true
[custom.WhiteHideBannerAd]
    65afa745b8141ba6b42c315a0031539d = 0
[custom.FeedLiveMids]
    75379081 = 1
    14135892 = 1
[custom.AIAdMis]
    108669 = 0
    111008012 = 1
[custom.AIAdGroupMid]
    14 = 1
    #1 = 1
    #2 = 1
    #0 = 1
[custom.AIAdGroupBuvid]
    3  = 1
    #1  = 1
    #2  = 1
    #3  = 1
    #4  = 1
    #5  = 1
    #6  = 1
    #7  = 1
    #8  = 1
    #9  = 1
    #10 = 1
    #11 = 1
    #12 = 1
    #13 = 1
    #14 = 1
    #15 = 1
    #16 = 1
    #17 = 1
    #18 = 1
    #19 = 1

[feed]
feedCacheCount = 200
liveFeedCount = 7
# index
[feed.index]
    count = 10
    iPadCount = 20
    moePosition = 6
    followPosition = 7
    abnormal = false
    interest = ["生活","游戏","影视","娱乐","二次元","音乐","科技","时尚","鬼畜","舞蹈"]
[feed.cmResource]
    "iphone"  = 1890
    "android" = 1897
    "ipad"    = 1975
[feed.followMode]
    title = "当前为首页推荐 - 关注模式（内测版）"
    option = [
        {title="通用模式",desc="开启后，推荐你可能感兴趣的内容",value=0},
        {title="关注模式（内测版）",desc="开启后，仅显示关注UP主更新的视频",value=1}
    ]
[feed.followMode.card]
    title = "启用首页推荐 - 关注模式（内测版）"
    desc = "我们根据你对bilibili推荐的反馈，为你定制了关注模式。开启后，仅为你显示关注UP主更新的视频哦。尝试体验一下？"
    button = ["暂不需要","立即开启"]

[showInfoc]
project = "app-feed"
name = "show"
proto = "tcp"
addr = "172.18.21.101:5403"
chanSize = 10240

[tagInfoc]
project = "app-feed"
name = "tag"
proto = "tcp"
addr = "172.18.21.101:5403"
chanSize = 10240

[redirectInfoc]
project = "app-feed"
name = "redirect"
proto = "tcp"
addr = "172.18.21.101:5403"
chanSize = 10240

[showInfoc2]
taskID = "000027"
proto = "tcp"
addr = "172.19.100.20:5401"
chanSize = 10240

[tagInfoc2]
taskID = "000028"
proto = "tcp"
addr = "172.19.100.20:5401"
chanSize = 10240

[redirectInfoc2]
taskID = "000029"
proto = "tcp"
addr = "172.19.100.20:5401"
chanSize = 10240

[host]
live     = "http://live.bilibili.co"
liveApi  = "http://api.live.bilibili.co"
bangumi  = "http://bangumi.bilibili.co"
data     = "http://data.bilibili.co"
hetongzi = "http://hetongzi.bilibili.co"
www      = "http://www.bilibili.com"
apiCo    = "http://api.bilibili.co"
api      = "http://api.bilibili.com"
ad       = "http://cm.bilibili.co"
activity = "http://matsuri.bilibili.co"
rank     = ""
show     = "http://show.bilibili.com"
dynamic  = "http://api.vc.bilibili.com"
dynamicCo  = "http://api.vc.bilibili.co"
bigData  = "http://bigdata.bilibili.co"
search   = "http://s.search.bilibili.co"
fawkes = "http://fawkes.bilibili.co"
black    = "http://172.18.7.208"

[hostDiscovery]
ad = "http://cm.bilibili.co"
data = "http://data.bilibili.co"

[xlog]
# dir = "/data/log/app-feed"
stdout=true

[cardDatabus]
    key = "8e27ab7e39270b59"
    secret = "477df6a068d7332a163f95abbad2079c"
    group = "AiCardJob-MainAppSvr-P"
    topic = "AiCardJob-T"
    action = "pub"
    offset = "new"
    name = "app-feed/cardsub"
    proto = "tcp"
    addr = "172.18.21.41:6205"
    active = 1
    idle = 1
    dialTimeout = "1s"
    readTimeout = "60s"
    writeTimeout = "1s"
    idleTimeout = "10s"

[app]
key    = "e7482d29be4a95b8"
secret = "9e803791cdef756e75faee68e12b7442"

[httpDataAd]
key = "6a29f8ed87407c11"
secret = "d3c5a85f5b895a03735b5d20a273bc57"
dial      = "100ms"
timeout   = "350ms"
keepAlive = "60s"
timer     = 1024

[httpNg]
key    = "6a29f8ed87407c11"
secret = "d3c5a85f5b895a03735b5d20a273bc57"
dial      = "1s"
timeout   = "2s"
keepAlive = "60s"

[httpClient]
key    = "e7482d29be4a95b8"
secret = "9e803791cdef756e75faee68e12b7442"
dial      = "30ms"
timeout   = "100ms"
keepAlive = "60s"
timer     = 128
[httpClient.breaker]
    window  = "10s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100

[httpClientAsyn]
key    = "e7482d29be4a95b8"
secret = "9e803791cdef756e75faee68e12b7442"
dial      = "1s"
timeout   = "2s"
keepAlive = "60s"
timer     = 10
[httpClientAsyn.breaker]
    window  = "10s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100

[httpData]
key    = "e7482d29be4a95b8"
secret = "9e803791cdef756e75faee68e12b7442"
dial      = "30ms"
timeout   = "200ms"
keepAlive = "60s"
timer     = 1024
[httpData.breaker]
    window  = "10s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100

[httpTag]
key    = "e7482d29be4a95b8"
secret = "9e803791cdef756e75faee68e12b7442"
dial      = "50ms"
timeout   = "200ms"
keepAlive = "60s"
timer = 10
    [httpTag.breaker]
    window  = "10s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100

[httpAd]
key    = "e7482d29be4a95b8"
secret = "9e803791cdef756e75faee68e12b7442"
dial      = "50ms"
timeout   = "100ms"
keepAlive = "60s"
timer = 128
[httpAd.breaker]
    window  = "10s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100

[httpActivity]
key    = "e7482d29be4a95b8"
secret = "9e803791cdef756e75faee68e12b7442"
dial      = "50ms"
timeout   = "150ms"
keepAlive = "60s"
timer = 128
[httpActivity.breaker]
    window  = "10s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100

[httpBangumi]
key    = "e7482d29be4a95b8"
secret = "9e803791cdef756e75faee68e12b7442"
dial      = "50ms"
timeout   = "150ms"
keepAlive = "60s"
timer = 128
[httpBangumi.breaker]
    window  = "10s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100

[httpDynamic]
key    = "e7482d29be4a95b8"
secret = "9e803791cdef756e75faee68e12b7442"
dial      = "200ms"
timeout   = "800ms"
keepAlive = "60s"
timer = 128
[httpDynamic.breaker]
    window  = "10s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100

[httpShow]
key    = "e7482d29be4a95b8"
secret = "9e803791cdef756e75faee68e12b7442"
dial      = "50ms"
timeout   = "150ms"
keepAlive = "60s"
timer = 128
[httpShow.breaker]
    window  = "10s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100

[httpSearch]
key    = "e7482d29be4a95b8"
secret = "9e803791cdef756e75faee68e12b7442"
dial      = "50ms"
timeout   = "150ms"
keepAlive = "60s"
timer = 128
[httpSearch.breaker]
    window  = "10s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100

[bm]
    [bm.outer]
    addr = "0.0.0.0:6221"
    timeout = "1s"

[mysql]
    [mysql.show]
    addr   = "172.18.33.49:3306"
    dsn    = "show:UJYgc9UkHIaGovEDUXpTU4U0rjBpZtwb@tcp(172.18.33.49:3306)/bilibili_show?timeout=1s&readTimeout=1s&writeTimeout=1s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 2
    idle   = 1
    queryTimeout = "1s"
    execTimeout = "1s"
    tranTimeout = "1s"
    [mysql.show.Breaker]
    window = "1s"
    sleep = "1s"
    bucket = 10
    ratio = 0.5
    request = 100
    [mysql.resource]
    addr = "172.18.33.49:3306"
    dsn = "resource:nMgVkY0JPgQr60nUVif5tEUbOTXlilXN@tcp(172.18.33.49:3306)/bilibili_resource?timeout=100ms&readTimeout=200ms&writeTimeout=200ms&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 2
    idle = 1
    queryTimeout = "1s"
    execTimeout = "1s"
    tranTimeout = "1s"
    [mysql.resource.Breaker]
    window = "1s"
    sleep = "1s"
    bucket = 10
    ratio = 0.5
    request = 100
    [mysql.manager]
    addr = "172.16.33.205:3308"
    dsn = "test:test@tcp(172.16.33.205:3308)/bilibili_manager?timeout=100ms&readTimeout=200ms&writeTimeout=200ms&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 2
    idle = 1
    queryTimeout = "1s"
    execTimeout = "1s"
    tranTimeout = "1s"
    [mysql.manager.Breaker]
    window = "1s"
    sleep = "1s"
    bucket = 10
    ratio = 0.5
    request = 100
[redis]
    [redis.feed]
    name   = "app-feed/feed"
    proto  = "tcp"
    addr   = "127.0.0.1:20435"
    active = 5
    idle   = 1
    dialTimeout  = "30ms"
    readTimeout  = "80ms"
    writeTimeout = "80ms"
    idleTimeout  = "80s"
    expireRecommend = "1h"
    expireBlack = "16h"
    [redis.feed2]
    name   = "app-feed/feed"
    proto  = "unix"
    addr   = "127.0.0.1:20435"
    active = 5
    idle   = 1
    dialTimeout  = "30ms"
    readTimeout  = "80ms"
    writeTimeout = "80ms"
    idleTimeout  = "80s"
    expireRecommend = "1h"
    expireBlack = "16h"
    [redis.upper]
    name   = "app-feed/upper"
    proto  = "unix"
    addr   = "127.0.0.1:20435"
    active = 5
    idle   = 1
    dialTimeout  = "30ms"
    readTimeout  = "50ms"
    writeTimeout = "50ms"
    idleTimeout  = "80s"
    expireUpper  = "96h"

[memcache]
    [memcache.feed]
    name   = "app-feed/feed"
    proto  = "unix"
    addr   = "/tmp/uat-app-mc.sock"
    active = 5
    idle   = 1
    dialTimeout  = "30ms"
    readTimeout  = "150ms"
    writeTimeout = "150ms"
    idleTimeout  = "80s"
    expireArchive = "24h"
    expireCache = "480h"
    [memcache.cache]
    name   = "app-feed/cache"
    proto  = "unix"
    addr   = "/tmp/uat-app-mc.sock"
    active = 5
    idle   = 1
    dialTimeout  = "30ms"
    readTimeout  = "150ms"
    writeTimeout = "150ms"
    idleTimeout  = "80s"
    expireCache  = "24h"

[dislikeDatabus]
key = "0QNB0ZgFozbKUCQhbTq8"
secret = "0QNB0ZgFozbKUCQhbTq9"
group= "TagDislike-SkyHorse-P"
topic= "Dislike-T"
action="pub"
name = "app-feed/dislike"
proto = "tcp"
addr = "172.18.33.50:6205"
active = 5
idle = 1
dialTimeout = "30ms"
readTimeout = "80ms"
writeTimeout = "80ms"
idleTimeout = "80s"
expire = "1h"

[cardAdFeedDatabus]
    key = "8e27ab7e39270b59"
    secret = "477df6a068d7332a163f95abbad2079c"
    group = "AdCardGif-MainAppSvr-P"
    topic = "AdCardGif-T"
    action = "pub"
    offset = "new"
    name = "app-feed/cardsub"
    proto = "tcp"
    addr = "172.22.42.40:6205"
    active = 1
    idle = 1
    dialTimeout = "1s"
    readTimeout = "60s"
    writeTimeout = "1s"
    idleTimeout = "10s"

[sessionRecordDatabus]
    key = "8e27ab7e39270b59"
    secret = "477df6a068d7332a163f95abbad2079c"
    group = "AppFeedClarifyData-MainAppSvr-P"
    topic = "AppFeedClarifyData-T"
    action = "pub"
    offset = "new"
    name = "app-feed/cardsub"
    proto = "tcp"
    addr = "172.22.42.40:6205"
    active = 1
    idle = 1
    dialTimeout = "1s"
    readTimeout = "60s"
    writeTimeout = "1s"
    idleTimeout = "10s"

[bnj]
tabImg = "http://i1.hdslb.com/bfs/archive/e51ec36d654559de9d2d197f4d77ee60302fa754.png"
tabID = 10

[hbase]
master = ""
meta = ""
dialTimeout = "100ms"
readTimeout = "100ms"
readsTimeout = "200ms"
writeTimeout = "200ms"
writesTimeout = "200ms"
    [hbase.zookeeper]
    root = ""
    addrs = ["172.18.33.131:2181", "172.18.33.168:2181", "172.18.33.169:2181"]
    timeout = "30s"

[buildLimit]
    NewActiveTabIOS = 8820
    NewActiveTabAndroid = 5499999
    NewChannelIOS = 8960
    NewChannelAndroid = 5509999

[cron]
    LoadCache = "@every 1m"
    LoadLiveCache = "@every 1s"

[storyInfoc2]
taskID = "004071"
proto = "tcp"
addr = "172.19.100.20:5402"
chanSize = 10240

[sampleConfig]
    probability = 0.001
    timeWindow = 0

[storyClickInfoc2]
taskID = "000025"
proto   = "tcp"
addr    = "uat-dataflow.bilibili.co:5401"
chanSize = 10240

[mogulDatabus]
    key = "8e27ab7e39270b59"
    secret = "477df6a068d7332a163f95abbad2079c"
    group = "Mogul-MainAppSvr-P"
    topic = "Mogul-T"
    action = "pub"
    name = "app-card/mogul"
    active = 30
    idle = 5
    dialTimeout = "200ms"
    readTimeout = "500ms"
    writeTimeout = "800ms"
    idleTimeout = "80s"