[Custom]
internal = "20s"

[Taishan]
table = "archive"
token = "archive"

[db]
    [db.archive]
    name = "bilibili_archive"
    dsn = "arc_service:lizK1PZWI7GrQDhuxsc3wtvXT04kRSo6@tcp(172.22.34.101:3306)/bilibili_archive?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8mb4"
    active = 5
    idle = 1
    idleTimeout = "4h"
    queryTimeout = "5s"
    execTimeout = "5s"
    tranTimeout = "5s"
    [db.result]
    name = "archive_result"
    dsn = "arc_service:lizK1PZWI7GrQDhuxsc3wtvXT04kRSo6@tcp(172.22.34.101:3306)/archive_result?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8mb4"
    active = 5
    idle = 1
    idleTimeout = "4h"
    queryTimeout = "5s"
    execTimeout = "5s"
    tranTimeout = "5s"

[[ArcRedises]]
    name = "archive-service/archive"
    proto = "tcp"
    addr = "127.0.0.1:20078"
    idle = 10
    active = 100
    dialTimeout = "100ms"
    readTimeout = "500ms"
    writeTimeout = "500ms"
    idleTimeout = "80s"
    expire = "8h"

[Cron]
    CheckModifyAids = "@every 10s"