
# This is a TOML document. Boom~
demoExpire = "24h"
abtesthost = "http://10.221.50.248:6193"
tushost = "http://uat-berserker.bilibili.co"
actionHost = "http://uat-manager.bilibili.co"
businessID = 368
editBusinessID = 370

[http]
key    = "e7482d29be4a95b8"
secret = "9e803791cdef756e75faee68e12b7442"
dial      = "100ms"
timeout   = "800ms"
keepAlive = "60s"
