[log]
dir = "/tmp/log/admin/activity/"

[auth]
    managerHost = "http://uat-manager.bilibili.co"
    dashboardHost = "http://dashboard-mng.bilibili.co"
    dashboardCaller = "manager-go"
    [auth.DsHTTPClient]
    key = "manager-go"
    secret = "949bbb2dd3178252638c2407578bc7ad"
    dial = "1s"
    timeout = "1s"
    keepAlive = "60s"
    [auth.DsHTTPClient.breaker]
    window  = "3s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100
    [auth.MaHTTPClient]
    key = "f6433799dbd88751"
    secret = "36f8ddb1806207fe07013ab6a77a3935"
    dial = "1s"
    timeout = "1s"
    keepAlive = "60s"
    [auth.MaHTTPClient.breaker]
    window  = "3s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100
    [auth.session]
    sessionIDLength = 32
    cookieLifeTime = 1800
    cookieName = "mng-go"
    domain = ".bilibili.co"
    [auth.session.Memcache]
    name = "go-business/auth"
    proto = "tcp"
    addr = "10.23.4.117:11211"
    active = 10
    idle = 10
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "80s"


[bws]
    startDay = 20190801
    endDay = 20190830
    startHour = 9
    endHour = 21
    ReserveSid = 12461
    bid = 9

[staff]
    PicSid = 10575

[lottery]
    AppKey = "nBF6jpB7"
    AppToken = "XZUGqmAf1rRmu7l0dhogFIPPvveHOgSy2WtQ957JPeE"
    VipAppKey = "33ac033ce123e590"
    SenderMidLimit = ["zhanghao09","zhangtianlong01","yichaofan","zhangtinghua","yangyi03","wangkan","zhangtianxing","dujinyang","zhufan"]
    moneylimit = ["zhanghao09","songchenyu","yichaofan","zhangtinghua","v_zhuzhangbing","yangyi03","sunruoyu","zhufan","jiaweiwei"]
    NumLimit = ["zhanghao09","songchenyu","yichaofan","zhangtinghua","v_zhuzhangbing","yangyi03","zhufan","jiaweiwei"]
    Reviewers = ["zhanghao09","zhangxiaoxi02","sunruoyu","zhangtianlong01","pengbo","songchenyu","yichaofan","zhangtinghua","yangyi03","wangkan","zhangtianxing","dujinyang","zhufan","songchenyu"]
	PublicKey          = "71f079db59672ecec5b8d6f252c4b59ab2a8a227mainsite@bilibili.com"
	AuditSubject       ="抽奖审核"
	AuditRejectSubject ="抽奖审核不通过"
	AuditPassSubject   ="抽奖审核通过"
    editLink = "http://uat-activity-template.bilibili.co/lottery/edit/"
    [lottery.MailInfo]
		Host = "smtp.partner.outlook.cn"
        Port = 587
        Pwd = "5Ztf9f23DOTHpkfx"
        Address = "yyjs-server@bilibili.com"
        [[lottery.MailInfo.ToAddress]] 
            address = "zhangtinghua@bilibili.com"
            name = "zhangtinghua"
        [[lottery.MailInfo.CcAddress]] 
            address ="zhangtinghua@bilibili.com"
            name = "zhangtinghua"
        [[lottery.MailInfo.BccAddresses]]
            address = "zhangtinghua@bilibili.com"
            name = "zhangtinghua"

[rank]
    ArchiveLength = 3
    Reviewers = ["yangyi03","jiaweiwei","zhangtinghua","zhangtianxing","zhufan"]
    Admin = ["zhangtinghua","niyingfeng"]
[GatherAddress]
    NotifyCode = "293_3"

[Up]
    SenderUid = 88895139
    PassContent = "您发起的ar活动已通过审核"
    UnPassContent = "很抱歉，您发起的ar活动未能通过审核，请重新发起活动"
    actSenderUid = 88895139

[Alarm]
    WeChatToken = "GYQeuDWBbAsCNeGz"
    WeChatSecret = "ZKpmgINTkianyMbMixyxcPQjMCSHCDrk"
    WeChatShareHost = "b23.tv"
    WeChatMonitorTick = "1h"
    Username = "yuhui01"
    AlarmTag = "【时尚分区活动-哔哩哔哩万事屋】"

[Wechat]
    AppId = "wx88251618c22c0c3f"
    Secret = "aa4b34e75db08be8624061a4906eb079"

[VogueActivity]
    ActPlatActivity = "fashion_618"
    ScoreInitialValue = 20
    Active = 0

[infocConf]
[infocConf.CloudInfoc]
  cloudLogID =004758
  
[rule]
    [rule.SpecReserveSids]
        "12061" = 1

[tunnelPush]
   oldReserveSubMax = 12208
   tunnelBizID = 1001
   dynamicCardTag = "活动"
   Index = ['{"template_id":1003,"titles":"你预约的#title#正在进行","contents":"#content#已开始，点击查看"}']
   Letter = ['{"template_id":1008,"titles":"活动开始提醒","contents":"你报名的#content1#已开始，#content2#点击查看更多"}']
   Dynamic = ['{"template_id":1004,"titles":"你预约的#title#正在进行","contents":"#content#已开始，点击查看"}']

[Reserve]
Notify = ["ouyangkeshou", "liqing01", "yehanlu"]

[S10Mail]
	FilePath="./data/"
	[S10Mail.MailInfo]
		Host = "smtp.partner.outlook.cn"
        Port = 587
        Pwd = "5Ztf9f23DOTHpkfx"
        Address = "yyjs-server@bilibili.com"
        [[S10Mail.MailInfo.ToAddress]] 
            address = "linqin@bilibili.com"
            name = "linqin"
        [[S10Mail.MailInfo.ToAddress]]
            address = "wuliang02@bilibili.com"
            name = "wuliang02"
        [[S10Mail.MailInfo.ToAddress]]
            address = "ouyangkeshou@bilibili.com"
            name = "ouyangkeshou"
       	[[S10Mail.MailInfo.ToAddress]]
            address = "huangtao02@bilibili.com"
            name = "huangtao02"
       	[[S10Mail.MailInfo.ToAddress]]
            address = "wangjing02@bilibili.com"
            name = "wangjing02"
        [[S10Mail.MailInfo.CcAddress]] 
            address ="ouyangkeshou@bilibili.com"
            name = "ouyangkeshou"
        [[S10Mail.MailInfo.BccAddresses]]
            address = "ouyangkeshou@bilibili.com"
            name = "ouyangkeshou"

[S10CacheExpire]
    SignedExpire = "5m"
    TaskProgressExpire ="10m"
    RestPointExpire = "1h"
    CoinExpire = "1m"
	PointExpire = "720h"
    LotteryExpire ="5m"
	ExchangeExpire="5m"
    RoundExchangeExpire="5m"
	RestCountGoodsExpire="5m"
    RoundRestCountGoodsExpire="5m"
    PointDetailExpire="5m"

[S10General]
    RedeliveryHost="http://uat-api.bilibili.co"
	SubTabSwitch=false
	Robins=[1,2,3,4,5]

[Boss]
Host = "http://uat-boss.bilibili.co"
AccessKeyID = "ed720dc0397edd39"
SecretAccessKey = "60ba2f5ce7f1c90cfc4da77517cc333f"

[tunnelGroup]
   source = "activity"

[notifier]
    mentionUserIDs = ["guanyanliang"]
    mentionUserTels = ["13472750574"]
    webhookUrl = "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=27c0aa66-5425-4d39-a8af-44090868bc32"


[Subject]
AuditGroupID = 119
[cards]
activity = "YouthWithYou"

[ActDomainConf]
    DomainListUrl   = "/x/activity/actdomain/list"
    DefaultPageNo   = 1
    DefaultPageSize = 50
    APIHost = "http://uat-api.bilibili.co"
    [ActDomainConf.FawkesConf]
        Host            = "http://fawkes.bilibili.co"
        Env             = "test"
        Operator        = "activity-admin"
        AddUrl          = "/x/admin/fawkes/business/config/default/add"
        GetUrl          = "/x/admin/fawkes/business/config/default"
        AppKey          = "android,android64,iphone,ipad2,android_b,iphone_b"
        Business        = "business_active_list_channel"
        Description     = "Description"
        ItemGroupName   = "business_active_list_channel"
        ItemDescription = "活动页自定义域名"
        ItemKey         = "custom_event_list"

[GaoKaoAnswer]
    SpitTag  = "$$$"
    BaseID = [10,11,12,13,14]