[orm]
    dsn = "lottery:D8B9aJcnMHh2SWzVvCQiIJ2qYzfMvfUg@tcp(172.22.34.101:3306)/bilibili_lottery?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 5
    idle = 5
    idleTimeout = "4h"

[TIDBORM]
    dsn = "lottery:D8B9aJcnMHh2SWzVvCQiIJ2qYzfMvfUg@tcp(172.22.34.101:3306)/bilibili_lottery?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 5
    idle = 5
    idleTimeout = "4h"

[mysql]
    [mysql.lottery]
    addr = "172.22.34.101:3306"
    dsn = "lottery:D8B9aJcnMHh2SWzVvCQiIJ2qYzfMvfUg@tcp(172.22.34.101:3306)/bilibili_lottery?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 5
    idle = 2
    idleTimeout ="4h"
    queryTimeout = "1s"
    execTimeout = "1s"
    tranTimeout = "2s"
    [mysql.lottery.breaker]
    window  ="3s"
    sleep   ="100ms"
    bucket  = 10
    ratio   = 0.5

[export]
    [export.lottery]
    addr = "172.22.34.101:3306"
    dsn = "lottery:D8B9aJcnMHh2SWzVvCQiIJ2qYzfMvfUg@tcp(172.22.34.101:3306)/bilibili_lottery?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 5
    idle = 2
    idleTimeout ="4h"
    queryTimeout = "1s"
    execTimeout = "1s"
    tranTimeout = "2s"
    [export.lottery.breaker]
    window  ="3s"
    sleep   ="100ms"
    bucket  = 10
    ratio   = 0.5

[S10MySQL]
    addr = "172.22.34.101:3306"
    dsn = "lottery:D8B9aJcnMHh2SWzVvCQiIJ2qYzfMvfUg@tcp(172.22.34.101:3306)/bilibili_lottery?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 5
    idle = 2
    idleTimeout ="4h"
    queryTimeout = "500ms"
    execTimeout = "500ms"
    tranTimeout = "500ms"
    [S10MySQL.breaker]
        window  ="3s"
        sleep   ="100ms"
        bucket  = 10
        ratio   = 0.5
        request = 100
[RewardsMySQL]
    addr = "172.22.34.101:3306"
    dsn = "lottery:D8B9aJcnMHh2SWzVvCQiIJ2qYzfMvfUg@tcp(172.22.34.101:3306)/bilibili_lottery?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 5
    idle = 2
    idleTimeout ="4h"
    queryTimeout = "500ms"
    execTimeout = "500ms"
    tranTimeout = "500ms"
    [RewardsMySQL.breaker]
        window  ="3s"
        sleep   ="100ms"
        bucket  = 10
        ratio   = 0.5
        request = 100