[Databus]
    target = "discovery://default/infra.databus.v2"
    app_id = "main.web-svr.esports"
    token = "4b6359ee1471e91fdece8e113204fcad"
    [Databus.Topic]
    BGroupMessage = "BGroupMessage-T"

[TunnelDatabusPub]
    key = "170e302355453683"
    secret = "3d0e8db7bed0503949e545a469789279"
    group = "TunnelRelation-MainCommunity-P"
    topic = "TunnelRelation-T"
    action = "pub"
    dialTimeout = "60ms"
    readTimeout = "200ms"
    writeTimeout = "500ms"
    idleTimeout = "10s"