[BM]
    addr = "0.0.0.0:7791"
    timeout = "1s"

[httpClient]
    key = "7c7ac0db1aa05587"
    secret = "9a6d62d93290c5f771ad381e9ca23f26"
    dial = "1s"
    timeout = "1s"
    keepAlive = "60s"
    timer = 1000

[elastic]
    host = "http://uat-api.bilibili.co"
    [elastic.HTTPClient]
    key = "7c7ac0db1aa05587"
    secret = "9a6d62d93290c5f771ad381e9ca23f26"
    dial = "100ms"
    timeout = "600ms"
    keepAlive = "60s"

[Limiter]
    Disable = false
    Preflight = false
    [[Limiter.Methods]]
    path = "/x/esports/s10/tab"
    rule = "total"

[host]
    search  = "http://s.search.bilibili.co"
    es      = "http://api.bilibili.co"
