[memcached]
    name = "esport/s10"
    proto = "tcp"
    addr = "10.23.4.117:11211"
    idle = 64
    active = 1024
    dialTimeout = "30ms"
    readTimeout = "200ms"
    writeTimeout = "200ms"
    idleTimeout = "80s"

[Memcached4UserGuess]
    name = "esport/s10"
    proto = "tcp"
    addr = "10.23.4.117:11211"
    idle = 64
    active = 1024
    dialTimeout = "30ms"
    readTimeout = "200ms"
    writeTimeout = "200ms"
    idleTimeout = "80s"

[autoSubCache]
    name = "esports"
    proto = "tcp"
    addr = "10.23.4.117:20111"
    idle = 10
    active = 10
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "10s"