[mysql]
    addr = "172.23.34.40:3308"
    dsn = "esports:DiVkYZmhjLbB2o7c6vaTrwqUlSfPCKWs@tcp(172.23.34.40:3308)/bilibili_esports?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 5
    idle = 2
    idleTimeout = "4h"
    queryTimeout = "800ms"
    execTimeout = "100ms"
    tranTimeout = "200ms"
    [mysql.breaker]
    window = "3s"
    sleep = "100ms"
    bucket = 10
    ratio = 0.5
    request = 100

[mysqlMaster]
    addr = "172.23.34.40:3308"
    dsn = "esports:DiVkYZmhjLbB2o7c6vaTrwqUlSfPCKWs@tcp(172.23.34.40:3308)/bilibili_esports?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 5
    idle = 2
    idleTimeout = "4h"
    queryTimeout = "500ms"
    execTimeout = "100ms"
    tranTimeout = "200ms"
    [mysqlMaster.breaker]
    window = "3s"
    sleep = "100ms"
    bucket = 10
    ratio = 0.5
    request = 100