[mysql]
    addr   = "172.22.34.101:3306"
    dsn    = "kvo:X5Cev8dr0PjCObmlvITxB9heDUPnTXS4@tcp(172.22.34.101:3306)/bilibili_kvo?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 5
    idle   = 2
    idleTimeout  = "4h"
    queryTimeout = "200ms"
    execTimeout  = "200ms"
    tranTimeout  = "200ms"
    [mysql.breaker]
        window = "1s"
        sleep = "100ms"
        bucket = 10
        ratio = 0.5
        request = 100
