reload = "1m"
patchLimit = 20
PatchSteadyLimit = 5
whitelist = ["yujia","zhangxin","caijian"]
zipContentType = ["application/zip","application/x-gzip"]
mobiAppWhiteList = ["android_bilithings"]

[cron]
    sessionID = "123"
    loadUsers = "@every 12h"
    loadApmParams = "@every 60m"
    loadVersion = "@every 60m"
    loadModuleListAll = "@every 30s"
    loadFawkesMoni = "@every 30s"
    loadFawkesMoniMergeNotice = "@every 5s"
    loadPackAll = "@every 30s"
    loadBizApkListAll = "@every 30s"
    loadTribeListAll = "@every 30s"
    loadUpgradConfigAll = "@every 30s"
    loadVersionAll = "@every 30s"
    loadHotfixAll = "@every 30s"
    loadFlowConfigAll = "@every 30s"

[xlog]
    dir = "/Users/data/log/fawkes/"

[httpServers]
    [httpServers.inner]
    addr = "0.0.0.0:7981"
    timeout = "1s"
    [httpServers.outer]
    addr = "0.0.0.0:7982"
    timeout = "1s"

[gitlab]
    host = "http://git.bilibili.co"
    api = "/api/v4"
    token = "StJAydUUEV755Fy2eriy"
    cronExpression = "*/20 * * * * *"

[wxnotify]
    accessTokenURL = "https://qyapi.weixin.qq.com/cgi-bin/gettoken?corpid=%s&corpsecret=%s"
    messageSendURL = "https://qyapi.weixin.qq.com/cgi-bin/message/send?access_token=%s"
    userlistURL = "https://qyapi.weixin.qq.com/cgi-bin/user/list?access_token=%s&department_id=%s&fetch_child=1"
    uploadTmpFileURL = "https://qyapi.weixin.qq.com/cgi-bin/media/upload?access_token=%s&type=%s"
    agentid = "1000098"
    corpid = "wx0000000000000000"
    corpsecret = "ir3QGXjWEtVh9tQ7AIxuboSRDCfg5YVTy7akHTG5"
    departmentIDs = "1552"

[comet]
    appId       = "fawkes"
    secretId    = "afdadifaodfoidhadif"
    signature   = "fiajfakfkpojfodjapj1677"
    cometUrl    = "http://comet.bilibili.co/notice/api/v4/message/send"
    workflowUrl = "http://comet.bilibili.co/api/v2/workflow/process/init"

[oss]
    accessKeyID = "LTAItAbov41J7Wea"
    accessKeySecret = "yaPQXRPLicxe8xLOgPsCffYEIO843a"
    endpoint = "http://oss-cn-shanghai.aliyuncs.com"
    bucket = "dl-hdslb-com"
    originDir = "mobile/test"
    publishDir = "mobile/latest"
    [oss.chinese]
        accessKeyID     = ""
        accessKeySecret = ""
        endpoint        = ""
        bucket          = ""
        originDir       = ""
        publishDir      = ""
        cdnDomain       = ""
    [oss.international]
        accessKeyID     = ""
        accessKeySecret = ""
        endpoint        = ""
        bucket          = ""
        originDir       = ""
        publishDir      = ""
        cdnDomain       = ""
    [oss.Inland]
        accessKeyID     = ""
        accessKeySecret = ""
        endpoint        = ""
        bucket          = ""
        originDir       = ""
        publishDir      = ""
        cdnDomain       = ""
    [oss.Abroad]
        accessKeyID     = ""
        accessKeySecret = ""
        endpoint        = ""
        bucket          = ""
        originDir       = ""
        publishDir      = ""
        cdnDomain       = ""

[appstoreconnect]
    expire = 1200
    audience = "appstoreconnect-v1"
    baseURL = "https://api.appstoreconnect.apple.com/v1/"
    iTMSTransporter = "/usr/local/itms/bin/iTMSTransporter"
    keyPath = "/test/itmspk/"
    testersThreshold = 5000
    buglyUploader = "/mnt/build-archive/buglySymboliOS.jar"
    disPermilLimit = 200

[mail]
    [mail.appBuilder]
        host = "smtp.partner.outlook.cn"
        port = 587
        address = "test@bilibili.com"
        pwd = "test"
        name = "App Builder"
    [mail.banBenJi]
        host = "smtp.exmail.qq.com"
        port = 465
        address = "test@smtp.bilibili.com"
        pwd = "test"
        name = "版本姬"

[cdn]
    secretid = "yasdfAgPsCffYEI"
    signature = "yaPQXRPLicxe8aqloseno"
    refreshURL = "http://gaia.bilibili.co/api/v1/cloud"
    refreshAction = "refresh_cache"
    refreshAccountIDs = "0,1,2"

[bfscdn]
    refreshURL = "http://sven.bilibili.co/x/admin/bfs/cache/purge?urls=%s"

[localPath]
    localDir    = "/work/project/fawkes"
    localDomain = "http://macross-jks.bilibili.co/archive/fawkes"
    cdnDomain   = "http://dl.hdslb.com"
    patcherPath = "/mnt/build-archive/patcher-1.8/bin/patcher"

[system]
    ios = ["8.0","8.1","8.2","8.3","8.4","9.0","9.1","9.2","9.3","10.0","10.1","10.2","10.3","11.0","11.1","11.2","11.3","11.4","12.0","12.1","12.2","12.3","13.0"]
    android = ["15","16","17","18","19","20","21","22","23","24","25","26","27","28","29"]

[host]
    easyst = "http://easyst.bilibili.co"
    saga   = "http://uat-saga-admin.bilibili.co"
    sven = "http://sven.bilibili.co"
    bap = "http://bap.bilibili.co"
    fawkes = "http://fawkes.bilibili.co"

[easyst]
    user = "fawkes-admin"
    platform = "platform_id"

[orm]
    dsn = "root:test@tcp(127.0.0.1:3306)/bilibili_fawkes?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8"
    active = 5
    idle = 2
    idleTimeout ="4h"

[mysql]
    [mysql.fawkes]
    name = "127.0.0.1:3306"
    dsn = "root:test@tcp(127.0.0.1:3306)/bilibili_fawkes?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8"
    active = 5
    idle = 2
    idleTimeout ="4h"
    queryTimeout = "1s"
    execTimeout = "1s"
    tranTimeout = "1s"
    [mysql.fawkes.breaker]
    window = "3s"
    sleep = "100ms"
    bucket = 10
    ratio = 0.5
    request = 100

    [mysql.macross]
    name = "127.0.0.1:3306"
    dsn = "root:test@tcp(127.0.0.1:3306)/bilibili_pack?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8"
    active = 5
    idle = 2
    idleTimeout ="4h"
    queryTimeout = "1s"
    execTimeout = "1s"
    tranTimeout = "1s"
    [mysql.macross.breaker]
    window = "3s"
    sleep = "100ms"
    bucket = 10
    ratio = 0.5
    request = 100

    [mysql.show]
    name = "127.0.0.1:3306"
    dsn = "root:test@tcp(127.0.0.1:3306)/bilibili_show?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 5
    idle = 2
    idleTimeout ="4h"
    queryTimeout = "1s"
    execTimeout = "1s"
    tranTimeout = "1s"
    [mysql.show.breaker]
    window = "3s"
    sleep = "100ms"
    bucket = 10
    ratio = 0.5
    request = 100

    [mysql.veda]
    name = "127.0.0.1:3306"
    dsn = "root:test@tcp(127.0.0.1:3306)/veda_crash_db?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 5
    idle = 2
    idleTimeout ="4h"
    queryTimeout = "1s"
    execTimeout = "1s"
    tranTimeout = "1s"
    [mysql.veda.breaker]
    window = "3s"
    sleep = "100ms"
    bucket = 10
    ratio = 0.5
    request = 100

[redis]
    [redis.fawkes]
        name = "fawkes-admin"
        proto = "tcp"
        addr = "127.0.0.1:6379"
        active = 1024
        idle   = 128
        dialTimeout = "1s"
        readTimeout = "1s"
        writeTimeout = "1s"
        idleTimeout = "10s"

[databus]
    discovery = "discovery://default/infra.databus.v2"
    appid = "main.app-svr.fawkes-admin"
    token = "84fba03ace2d0e1d01994d8e8eefe880"
    [databus.topics]
        packGreyDataPub = "pack-grey-data-Uat-T"


[broadcastGrpc]
    [broadcastGrpc.laser]
        token = "uat-laser"
        targetPath = "/bilibili.broadcast.v1.Laser/WatchLogUploadEvent"
    [broadcastGrpc.laserCommand]
        token = "uat-laser-watch-event"
        targetPath = "/bilibili.broadcast.v2.Laser/WatchEvent"
    [broadcastGrpc.module]
        token = "uat-mod-test"
        targetPath = "/bilibili.broadcast.message.fawkes/Module"
        ratelimit = 100
    [broadcastGrpc.sgpproxy]
        host = "pre-grpc-proxy.biliintl.co"
        discoveryId = "testpush.service.broadcast"

[clickhouse]
    [clickhouse.monitor]
        addr = "127.0.0.1:9000"
        name = "127.0.0.1:9000"
        dsn = "tcp://127.0.0.1:9000?username=default&database=bilibili_mobile_monitor&read_timeout=10&write_timeout=20"
        active = 5
        idle = 2
        idleTimeout ="4h"
        queryTimeout = "1s"
        execTimeout = "1s"
        tranTimeout = "1s"
        [clickhouse.monitor.breaker]
        window = "3s"
        sleep = "100ms"
        bucket = 10
        ratio = 0.5
        request = 100
    [clickhouse.monitor2]
            addr = "10.23.245.85:8123"
            name = "10.23.245.85:8123"
            dsn = "tcp://10.23.245.69:9000?username=default&database=bilibili_mobile_monitor&read_timeout=10&write_timeout=20"
            active = 5
            idle = 2
            idleTimeout ="4h"
            queryTimeout = "1s"
            execTimeout = "1s"
            tranTimeout = "1s"
            [clickhouse.monitor2.breaker]
            window = "3s"
            sleep = "100ms"
            bucket = 10
            ratio = 0.5
            request = 100
    [clickhouse.monitor3]
        addr = "127.0.0.3:9000"
        name = "127.0.0.3:9000"
        dsn = "tcp://127.0.0.3:9000?username=default&database=bilibili_mobile_monitor&read_timeout=10&write_timeout=20"
        active = 5
        idle = 2
        idleTimeout ="4h"
        queryTimeout = "1s"
        execTimeout = "1s"
        tranTimeout = "1s"
        [clickhouse.monitor3.breaker]
        window = "3s"
        sleep = "100ms"
        bucket = 10
        ratio = 0.5
        request = 100

[httpClient]
    key     = "f022126a8a365e20"
    secret  = "b7b86838145d634b487e67b811b8fab2"
    dial = "500ms"
    timeout = "2s"
    keepAlive = "60s"
    timer = 1000
        [httpClient.breaker]
        window  ="10s"
        sleep   ="10ms"
        bucket  = 10
        ratio   = 0.1
        request = 10

[auth]
    managerHost = "http://macross.bilibili.co"
    dashboardHost = "http://dashboard-mng.bilibili.co"
    dashboardCaller = "android-apk"
    [auth.DsHTTPClient]
    key     = "manager-go"
    secret  = "2pnik62rr8xgrrleag2vx2l0svvnrfld"
    dial = "1s"
    timeout = "1s"
    keepAlive = "60s"
    [auth.DsHTTPClient.breaker]
    window  = "3s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100
    [auth.MaHTTPClient]
    key     = "f022126a8a365e20"
    secret  = "b7b86838145d634b487e67b811b8fab2"
    dial = "1s"
    timeout = "1s"
    keepAlive = "60s"
    [auth.MaHTTPClient.breaker]
    window  = "3s"
    sleep   = "100ms"
    bucket  = 10
    ratio   = 0.5
    request = 100
    [auth.session]
    sessionIDLength = 32
    cookieLifeTime = 1800
    cookieName = "mng-go"
    domain = ".bilibili.co"
    [auth.session.Memcache]
    name = "go-business/auth"
    proto = "tcp"
    addr = "172.18.33.61:11232"
    active = 10
    idle = 10
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "80s"
[ep]
    monkeyUrl="http://uat-jenkins.bilibili.co/job/fawkes_monkey_hooker/buildWithParameters"
    monkeyAuth="fawkes1:asdadasdkhakhjkhkjahsdkjahdjkha"

[keys]
aesKey = "5a5g148a5f4a5f4a"


[bossConfig]
    host = "http://uat-boss.bilibili.co"
    accessKeyID = "56be3f1296b814ce"
    secretAccessKey = "4b61c259fbe2ad0f0f5ebc0f1be30737"

[mod]
    [mod.cdn]
        "/appstaticboss/"  = {oldDomain="https://upos-sz-static.hdslb.com",newDomain="https://upos-sz-staticcos.bilivideo.com",bucket=100}
    [mod.modCDN]
        "/bfs/app-static/" = "https://i0.hdslb.com"
        "/appstatic/"      = "https://boss.hdslb.com"
    [mod.disableModule]
        bplus = ["clip_image"]
        live = ["liveStreamingConfig"]
        mall = ["and_tflite","mall_box_detection_resource_ios","and-v8engine","and-bcanvas","test-v8-bcanvas"]
        pink = ["h5space"]
    [mod.poolKey]
        "9h6b73Kd4wP9" = ["mall"]
        "2YUAg25FgGZn" = ["feOffline"]
    [mod.priorityMod]
        "feOffline" = []
        "mall" = ["bilinternalfbfbb62256c6442f","bilinternal424586703acbf9b0","bilinternal8f8cec0a00c3e5c2","bilinternalfb7483fe63648bba"]

[broadcastPush]
    qps = 100
    operation = 1001
    url = "http://api.bilibili.co/x/internal/broadcast/push/all"
    expire = "20m"

[AlarmReceiver]
    UploadMonitorReceiver = ["luweidan"]
    EventMonitorReceiver = ["sunzhiyong01"]
    ChannelPackAutoBuildReceiver = ["luweidan"]

[prometheus]
    [prometheus.localPath]
        localDir = "/mobile-ep/apm-prometheus-config/mobile_monitor/release"
    [Prometheus.database]
        name = "database"
        host = "127.0.0.1"
        port = 8080
        user = "-"
        password = "-"

[flinkJob]
    [flinkJob.localPath]
        localDir = "/mobile-ep/apm-flink-config/mobile_monitor"

[moni]
    [moni.longMerge]
    duration = "5m"
    statisticalDuration = "2h"

[switch]
    [switch.packAutoUploadCDN]
        whiteList = ["w19e"]

[datacenter]
    host = "http://uat-berserker.bilibili.co"
    dir  = "/app-event/sys-event"
    add  = "/save-api"
    update = "/edit-api"
    delete = "/delete-api"
    [datacenter.openAPI]
        account   = "p_main_mobile"
        dir       = "/voyager/v1/invocation/grpc"
        secretKey = "06f796ff4db6b9eab2866c4dced1b510"

[billions]
    host                = "http://uat-billions.bilibili.co"
    dir                 = "/api/v1"
    autoAdd             = "/apps/auto"
    mappingUpdate       = "/app/mapping/fields/update"
    lifecycle           = "/app/lifecycle"
    treeId              = "mobile.mobile-ep.mobile-elasticsearch"
    deployLocations     = "000069"
    authorizationToken  = "3fb241bd5b1e4bf7ac7ec317ea2df067"
    cluster             = "mobile01"

[billionsAlert]
    host     = "https://uat-cloud.bilibili.co"
    dir      = "/billions"
    alert    = "/elastalert/api/v2/rule"
    ruleOpt  = "/elastalert/api/v2/rule-operation"
    token    = "b01fc2eabe822ade05dab3e2e22d7c51325b3cb2"

[elasticsearchProxy]
    host    = "http://billions-proxy.bilibili.co"
    dir     = "/api/v2"
    search  = "/_search"
    cluster = "mobile01"
    token   = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiIxIiwiaXNzIjoiMSJ9.bs-nPt7qTnhB24LxEGjTXnmnBMHhxSFDSdsfr"

[ipdb]
    ipv4 = "/tools/ipdb/ipv4.ipdb"

[task]
    [task.nasclean]
        [task.nasclean.cidelete]
            packType = [1, 3, 5, 6, 8]
            persistence = 3 #保留时长 单位月
            Start = 2021-03-27T05:45:00Z
            End = 2021-03-28T05:45:00Z
            AppKey = "w19e"
        [task.nasclean.patchdelete]
            AppKey = ["w19e"]
            ExcludeAppKey= ["android"]
            persistence = 3 #保留时长 单位月
        [task.nasclean.channeldelete]
            AppKey = ["w19e"]
            ExcludeAppKey= ["android"]
            persistence = 3 #保留时长 单位月
    [task.movetribe]
        apps = ["w19e"]
        oldDir = "/mnt/build-archive/archive/fawkes/pack/"
        newDir = "/mnt/build-archive/archive/fawkes/tribe/"
        oldUrl = "https://macross-jks.bilibili.co/archive/fawkes/pack/"
        newUrl = "https://macross-jks.bilibili.co/archive/fawkes/tribe/"
        batchSize = 10
        batch = 1
    [task.vedaupdate]
        apps = ["android","android64"]
        persistence = 6 #更新多久之前的数据 单位月
        count = 1000

[tapd]
    token=""

[exepath]
    [exepath.tribe]
        tribeapi = ""

[prometheusTemplate]
        key   = "__RELEASE_PKG_CONDITIONS__"
        value = "test"

